In [1]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in C:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages (26.7.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.2.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

##Data Imported to Database

In [3]:
import pandas as pd
import mysql.connector
from getpass import getpass

# csv file path -> table name (order matters if you have foreign keys)
files = {
    r"C:\Users\hp\Desktop\pe\products_cleaned.csv":   "products",
    r"C:\Users\hp\Desktop\pe\cleaned_user_N.csv":   "users",
    r"C:\Users\hp\Desktop\pe\sessions.csv":    "sessions",
    r"C:\Users\hp\Desktop\pe\interactions_cleaned.csv":      "interactions",
    r"C:\Users\hp\Desktop\pe\purchases_cleaned.csv": "purchases",
    r"C:\Users\hp\Desktop\pe\reviews.csv": "reviews",
}

conn = mysql.connector.connect(
    host="127.0.0.1",
    user="root",
    password=getpass("MySQL password: "),
    database="E_Commerce_Customer_Intelligence"
)
cursor = conn.cursor()

for path, table in files.items():
    df = pd.read_csv(path)
    df = df.astype(object).where(pd.notnull(df), None)  # NaN -> NULL

    cols = ", ".join(f"`{c}`" for c in df.columns)
    placeholders = ", ".join(["%s"] * len(df.columns))
    sql = f"INSERT INTO `{table}` ({cols}) VALUES ({placeholders})"

    cursor.executemany(sql, df.values.tolist())
    conn.commit()
    print(f"{table}: {cursor.rowcount} rows inserted")

cursor.close()
conn.close()

MySQL password: ··········
products: 1000 rows inserted
users: 10000 rows inserted
sessions: 19315 rows inserted
interactions: 100000 rows inserted
purchases: 1737 rows inserted
reviews: 1253 rows inserted

##Data Fetching from database

In [5]:
import csv
import mysql.connector

# TODO: Replace 'YOUR_MYSQL_PASSWORD' with your actual local MySQL root password
conn = mysql.connector.connect(
    host="127.0.0.1",
    user="root",
    password="Ak@shuniyal97",
    database="E_Commerce_Customer_Intelligence"
)

cursor = conn.cursor()

In [6]:
cursor = conn.cursor()

cursor.execute("SHOW TABLES")

for table in cursor.fetchall():
    print(table[0])

interactions
products
purchases
reviews
sessions
users

In [7]:
import pandas as pd

In [13]:
q="""
  SELECT
    ROUND(COALESCE(SUM(total_amount), 0), 2)
        AS total_revenue,

    COUNT(DISTINCT order_id) AS total_orders,
    COUNT(DISTINCT user_id) AS purchasing_customers,
    SUM(quantity) AS total_units_sold,
    ROUND(
        COALESCE(SUM(total_amount), 0)
        / NULLIF(COUNT(DISTINCT order_id), 0),
        2
    ) AS average_order_value
FROM purchases;
"""
df=pd.read_sql(q,conn)
df

C:\Users\hp\AppData\Local\Temp\ipykernel_24468\1723189479.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(q,conn)

,total_revenue,total_orders,purchasing_customers,total_units_sold,average_order_value
0,129510.85,1440,1287,2339.0,89.94

##Monthly Revenue

In [14]:
q="""
  SELECT
    DATE_FORMAT(order_date, '%Y-%m-01') AS sales_month,
    ROUND(SUM(total_amount), 2) AS revenue,
    COUNT(DISTINCT order_id) AS total_orders,
    COUNT(DISTINCT user_id) AS unique_customers,
    SUM(quantity) AS units_sold
FROM purchases
GROUP BY DATE_FORMAT(order_date, '%Y-%m-01')
ORDER BY sales_month;
"""
df=pd.read_sql(q,conn)
df

C:\Users\hp\AppData\Local\Temp\ipykernel_24468\3401257369.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(q,conn)

   sales_month  revenue  total_orders  unique_customers  units_sold
0   2023-01-01   197.24             3                 3         6.0
1   2023-02-01  1124.23            11                11        22.0
2   2023-03-01  2706.91            32                28        49.0
3   2023-04-01  1918.38            23                21        42.0
4   2023-05-01  2552.58            24                23        44.0
5   2023-06-01  2549.52            26                24        41.0
6   2023-07-01  1904.17            23                23        33.0
7   2023-08-01  1487.89            16                15        28.0
8   2023-09-01  1469.43            22                22        35.0
9   2023-10-01  3587.70            24                23        44.0
10  2023-11-01  2049.66            21                20        30.0
11  2023-12-01  2063.09            24                24        40.0
12  2024-01-01  2511.41            35                32        50.0
13  2024-02-01  2449.95            26                25        42.0
14  2024-03-01  2766.89            40                40        66.0
15  2024-04-01  3612.11            30                28        63.0
16  2024-05-01  1411.80            23                20        28.0
17  2024-06-01  2332.13            21                19        34.0
18  2024-07-01  3276.74            32                32        52.0
19  2024-08-01  5034.89            41                36        76.0
20  2024-09-01  2412.32            32                32        49.0
21  2024-10-01  3308.44            52                49        90.0
22  2024-11-01  3352.63            35                33        57.0
23  2024-12-01  4634.59            46                42        78.0
24  2025-01-01  3780.87            48                46        74.0
25  2025-02-01  3876.88            48                46        75.0
26  2025-03-01  4719.14            51                50        91.0
27  2025-04-01  3800.39            41                41        67.0
28  2025-05-01  2944.69            45                44        62.0
29  2025-06-01  5490.95            57                49        84.0
30  2025-07-01  3916.39            44                38        73.0
31  2025-08-01  4940.07            60                59        93.0
32  2025-09-01  2725.07            33                33        61.0
33  2025-10-01  3791.32            41                37        65.0
34  2025-11-01  4454.80            35                35        60.0
35  2025-12-01  3298.09            42                38        62.0
36  2026-01-01  4046.76            44                41        68.0
37  2026-02-01  5249.97            46                43        71.0
38  2026-03-01  3397.72            40                36        69.0
39  2026-04-01  3308.77            51                46        80.0
40  2026-05-01  5054.27            52                49        85.0

##Daily sales trends

In [16]:
q="""
  SELECT
    DATE(order_date) AS sales_date,
    ROUND(SUM(total_amount), 2) AS daily_revenue,
    COUNT(DISTINCT order_id) AS orders,
    SUM(quantity) AS units_sold
FROM purchases
GROUP BY DATE(order_date)
ORDER BY sales_date;
"""
df=pd.read_sql(q,conn)
df

C:\Users\hp\AppData\Local\Temp\ipykernel_24468\449052845.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(q,conn)

     sales_date  daily_revenue  orders  units_sold
0    2023-01-15          11.48       1         2.0
1    2023-01-19         158.84       1         2.0
2    2023-01-31          26.92       1         2.0
3    2023-02-04         271.88       1         4.0
4    2023-02-06         121.90       1         1.0
..          ...            ...     ...         ...
825  2026-05-27          10.52       1         1.0
826  2026-05-28         205.78       2         5.0
827  2026-05-29          31.74       1         2.0
828  2026-05-30         289.62       1         3.0
829  2026-05-31         289.67       4         8.0

[830 rows x 4 columns]

##Revenue by year and quarter

In [18]:
q="""
  SELECT
    EXTRACT(YEAR FROM order_date) AS sales_year,
    EXTRACT(QUARTER FROM order_date) AS sales_quarter,
    ROUND(SUM(total_amount), 2) AS revenue,
    COUNT(DISTINCT order_id) AS orders
FROM purchases
GROUP BY
    EXTRACT(YEAR FROM order_date),
    EXTRACT(QUARTER FROM order_date)
ORDER BY sales_year, sales_quarter;
"""
df=pd.read_sql(q,conn)
df

C:\Users\hp\AppData\Local\Temp\ipykernel_24468\2218361842.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(q,conn)

    sales_year  sales_quarter   revenue  orders
0         2023              1   4028.38      46
1         2023              2   7020.48      73
2         2023              3   4861.49      61
3         2023              4   7700.45      69
4         2024              1   7728.25     101
5         2024              2   7356.04      74
6         2024              3  10723.95     105
7         2024              4  11295.66     133
8         2025              1  12376.89     147
9         2025              2  12236.03     143
10        2025              3  11581.53     137
11        2025              4  11544.21     118
12        2026              1  12694.45     130
13        2026              2   8363.04     103

##Find the top 20 customers by spending

In [20]:
q="""
  SELECT
    u.user_id,
    u.country,
    u.city,
    u.loyalty_tier,
    COUNT(DISTINCT p.order_id) AS total_orders,
    SUM(p.quantity) AS units_purchased,
    ROUND(SUM(p.total_amount), 2) AS total_spent
FROM users u
JOIN purchases p
    ON u.user_id = p.user_id
GROUP BY
    u.user_id, u.country, u.city, u.loyalty_tier
ORDER BY total_spent DESC
LIMIT 20;
"""
df=pd.read_sql(q,conn)
df

C:\Users\hp\AppData\Local\Temp\ipykernel_24468\2035929743.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(q,conn)

,user_id,country,city,loyalty_tier,total_orders,units_purchased,total_spent
0,6b888357-4601-4b33-8543-6ca73a7f7b04,US,Jacobsonshire,bronze,1,6.0,1486.54
1,1d915659-c9f5-4c24-947d-ac08255d6130,CA,Markport,silver,1,3.0,889.77
2,fa5cefb0-2f37-485c-80a3-7df4ecffd90b,FR,Paul-sur-Mer,bronze,1,2.0,885.30
3,84b90ed5-de66-4334-9106-77cab2fefe5d,US,Port Melissamouth,bronze,1,3.0,773.02
4,fd5f1634-99b8-4950-b0b0-09903e2a1ac9,KR,연천군,bronze,1,4.0,732.96
5,68037692-db83-40a6-a183-bcac6b43ef64,FR,Sainte Julesdan,bronze,1,2.0,667.35
6,b9e5bd2d-ad50-416f-ba4e-6f6e37111919,US,Petersonton,bronze,1,2.0,585.09
7,2ac29460-6138-4c29-bbf7-3e3b05cd514d,SG,Phillipsland,bronze,1,1.0,548.64
8,8c08b507-1f47-4e21-beb5-258709f5c6d3,US,Port Kathleen,silver,1,2.0,544.65
9,c7d4af0f-6f0b-45fd-b222-7316c071f512,US,North Danielleberg,bronze,1,1.0,541.90
10,4b01b99f-3b09-4eac-99cd-8f362e6de223,GB,Grahamshire,bronze,1,3.0,514.63
11,ab4978d3-d7a4-4bc4-b6ce-fb58803f5d83,IT,Bosco Di Galliera,silver,1,1.0,508.82
12,d8977edb-6e78-40f2-9892-801621a9b32d,AU,Carrollstad,bronze,1,2.0,506.04
13,bf1ee143-eea7-4b6d-b3db-bd8fdf344256,ES,León,bronze,3,4.0,498.49
14,fa3016cd-099f-44f8-becd-d712f0344c3f,FR,Colas,bronze,1,4.0,497.11
15,d7e8b18a-5ba0-47f1-ac7b-c9a65a60e095,SE,Norrköping,bronze,2,3.0,489.59
16,8391e2bc-db17-477f-a417-b9ca66827a79,US,Beasleyhaven,silver,2,9.0,484.12
17,589fdcd7-c1f7-4b9a-a2b1-d04bcc28aa5a,JP,川崎市宮前区,bronze,1,4.0,473.24
18,5aca5022-a81b-4c9b-af11-5e3f04fa7db9,AU,Stephenchester,bronze,2,3.0,470.77
19,b112e838-3815-4ca9-b982-ea4afc0c72a1,US,West Ethan,platinum,1,2.0,456.22

##Identify repeat customers

In [23]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [24]:
q="""
  SELECT
    user_id,
    COUNT(DISTINCT order_id) AS order_count,
    ROUND(SUM(total_amount), 2) AS total_spent
FROM purchases
GROUP BY user_id
HAVING COUNT(DISTINCT order_id) > 1
ORDER BY order_count DESC, total_spent DESC;
"""
df=pd.read_sql(q,conn)
df

C:\Users\hp\AppData\Local\Temp\ipykernel_24468\860013552.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(q,conn)

                                  user_id  order_count  total_spent
0    a35e6564-b69d-4a62-86f7-c500e1c2422e            4        78.78
1    bf1ee143-eea7-4b6d-b3db-bd8fdf344256            3       498.49
2    f0437b46-0861-4f8a-a3cb-c7400e1cfe20            3       409.10
3    c20d4c44-5b48-4450-b06c-0a8eef6fae05            3       367.90
4    0f7a21f8-40fc-4d44-99cf-9eaf87ba344f            3       322.22
5    63d77def-8408-4c23-b7da-9b0d40922301            3       302.62
6    d7e8b18a-5ba0-47f1-ac7b-c9a65a60e095            2       489.59
7    8391e2bc-db17-477f-a417-b9ca66827a79            2       484.12
8    5aca5022-a81b-4c9b-af11-5e3f04fa7db9            2       470.77
9    8331e250-14fa-4372-99fc-ea646c6975e8            2       447.47
10   457e7030-8f82-4152-868d-d32b907d6c8d            2       440.65
11   c4effe05-debf-4575-a7bc-d5aa5990b753            2       427.88
12   6e96e86d-b22f-40ce-afc9-2e9686d7c1a5            2       395.97
13   5136c54d-f27f-4199-ae4d-8ec9c76dd0dd            2       380.29
14   d2e3097a-6a6b-4b0f-b1c5-0323173f96ff            2       375.80
15   71e3e3e3-0004-4a08-84e9-81862aafb81d            2       358.65
16   80d2b0e5-d70f-4a58-b9db-2901c52d469a            2       357.75
17   bf7e5715-b739-4738-8f92-b2d2e47c9699            2       351.90
18   1287c0cb-1161-4208-ae2e-790d34270c62            2       350.56
19   a8bfef09-c030-4482-bddb-136cc7799f34            2       347.74
20   64954cc7-eda9-413e-836c-61aaf13a8979            2       330.13
21   ce7dd013-2d67-40b4-9cb0-00994e2a3bef            2       312.83
22   46fbd9e7-d8b7-48e1-a4b4-3ac5da09481b            2       302.94
23   f952faf5-e48a-44e6-ae56-183beb097f7c            2       299.26
24   7b59123f-9a18-41e0-8f4a-da1cd2de974a            2       299.19
25   c1fa0a7a-2d7d-48e0-a586-00a2d079dfd0            2       297.46
26   9e5efb95-69b2-4736-8706-0315f238b9e2            2       293.31
27   4ec418b2-7c11-4fb5-b352-562c6e89cff8            2       280.03
28   0311e99c-1613-43ec-8a01-1b4e80939c9b            2       265.73
29   31d63c1d-5a7f-486c-a6db-a655cbc082f5            2       256.47
30   ddc977fc-f40b-4d28-abb4-a43e9612b52d            2       255.27
31   899b4f7f-ebfc-46d0-a711-c103850c12cb            2       254.97
32   5309ff2a-c669-4b0e-b89b-bd8916a0dcaa            2       254.47
33   0b28cf81-b7b3-4dff-bcbd-c278eaca7f7a            2       235.63
34   d774c7a8-e8a7-4379-a26e-2f1299b393fc            2       228.92
35   ca2b28ab-d93a-4118-8006-c1d8fb620474            2       228.07
36   486fad11-e577-4c56-a4cd-d6e2818ba945            2       224.79
37   edd754cb-615f-47db-940c-144387cfb8bd            2       216.93
38   5b3d594f-c119-4dd4-a5c8-c4758791e9ce            2       197.98
39   8b748146-5cfa-48e4-9543-4767540c4516            2       197.42
40   31f3bc2e-3870-4b9d-a938-86cce57c02cb            2       196.11
41   5c2c665f-2810-43c0-9f39-f13b7fda3b3d            2       193.83
42   41a3faf4-8c99-4633-bfab-ecc1af8fc8fe            2       192.15
43   7c46cf08-1deb-4e06-85e3-3769827308b2            2       187.56
44   df43b497-e75f-406f-af0e-234d3bff00ef            2       186.22
45   34681f0f-ad1c-4c0d-85a3-bfc1b53889b8            2       184.04
46   74fcced9-19f5-4465-98f5-31ffa9433d2e            2       170.78
47   3a5a52ad-f21a-4ecf-a949-4b8c2bbd876e            2       168.57
48   21853536-4ecb-48e8-a96f-f289fb187fcd            2       166.40
49   94d82ed9-d787-4f86-9bda-b0680081ab2c            2       165.98
50   c0a21466-51f4-44c6-adfd-d4b5c868b4ca            2       165.63
51   95987c13-861c-4b45-849c-c3938912c262            2       164.23
52   75f5bb5e-7492-430f-8d0a-6e8eb161f276            2       164.02
53   8e75284b-0615-480f-9875-6b6c580f05ed            2       162.81
54   c030f4da-2076-4cb8-95b5-59e6e054c737            2       162.55
55   557d5238-2f16-499b-8cd0-0a14fa593ad4            2       162.09
56   5fcfefe7-1f13-4396-a148-4c85e3f82236            2       161.50
57   1b9c17b4-7b36-4fa4-b8e3-5adc01d0de11            2       160.09
58   6010d0db-7e2e-4a2a-9a0a-8dd229bfbf49            2       156.51
59   8ef7011f-038c-4941-a95b-d4ca663048f9            2       154.11
60   8146e3d1-fe6c-4796-8b31-25d9f95b2167            2       151.45
61   0094df58-edfe-4ecf-b214-94180bb4116e            2       151.34
62   a3cf009c-a949-4612-a91d-54c0c6076472            2       146.37
63   a6010976-9d6b-4993-9eca-29924f85746f            2       145.70
64   bc962be1-b13a-4a94-8b66-b2164136f370            2       144.86
65   5f92908d-d358-4792-8675-c47c79f0785f            2       142.14
66   011cb619-3e69-47bd-913c-670ecea4383c            2       141.93
67   5f1c6595-0317-451e-a5a0-a0878c202a07            2       140.61
68   09d2a48e-581c-4ab4-a02a-827c8c917126            2       140.07
69   a89b4e4d-e200-4c8c-8da9-45de4629dafe            2       139.40
70   df202215-7e65-4fb2-8aae-6cebcc972625            2       139.23
71   781f47b9-57fb-47c4-bea9-1f617431c4b4            2       138.78
72   ed908c6a-c745-47fc-ba56-d1bb70c169b8            2       136.45
73   dd0c768f-6a39-469f-ae84-5dfdf746d763            2       136.14
74   f7f915ec-03ba-470f-9105-b6343f458706            2       134.62
75   de8dcf4a-e4b6-47a5-ba65-c7646dcd0fdc            2       134.58
76   3b2552ec-8714-4c94-b09b-1fce1bab8f05            2       133.49
77   274b5d1e-5497-472e-afec-932869022c87            2       131.75
78   496cbf7d-16c9-457b-8ce6-8e72894d0c6f            2       131.08
79   a5a72214-1524-4689-9ccd-6975db8628e9            2       128.27
80   ddc8b9e9-73f1-4870-abdc-f809086dd3c1            2       127.65
81   740e837c-3460-4fdd-8bdd-c6c11200d536            2       126.31
82   cbcd72a1-764e-4c8e-a35b-faf8eef5e7f5            2       125.22
83   6aac1e5a-fc46-4ca8-9f99-5db1cc8710d5            2       125.01
84   d74b2d27-83c9-4d3b-b650-ff3f91f9e1e7            2       123.80
85   93c5234a-e761-44e5-96ad-a07379c810e9            2       122.34
86   17efb65b-2978-4153-ab72-fa35929327f8            2       121.45
87   5aed3b21-9c54-43a7-8df9-a2832a732acf            2       121.08
88   e3a664be-bd4a-4b22-a0e0-12fc42ee16ac            2       120.55
89   328d0584-072f-4928-a85d-28d91c869147            2       117.01
90   b0f16fe8-1f1d-461c-b7ab-253775d7a923            2       116.17
91   d0e031e9-4c97-475c-b301-3b9f6cb00a05            2       112.59
92   d3d288fa-d84d-4ae4-9a03-3f29ccc858bc            2       111.55
93   c00b75b4-3407-47bc-a76c-2aee0bb8a680            2       111.32
94   7ec02599-27fb-4426-85e8-0cede054ca98            2       110.73
95   a62fcf77-10b9-418b-aadc-e90e9d506e49            2       110.68
96   6fedb2d5-6d74-4726-a492-2e08d5ad070c            2       101.18
97   a088f40d-8236-49f8-9657-9ab53ca9259f            2        98.66
98   5f7fb809-8a08-4afc-bce8-ebd6a6e549a7            2        98.41
99   605caac2-d119-413a-ab11-caabb21f6a8f            2        95.98
100  74b3621b-fbf6-4089-b931-b68e0022f507            2        95.89
101  26807ddb-1064-4df0-b0e9-d564fa6c096d            2        95.86
102  7c3f062b-e33e-4970-b8bc-eb3c881ab41c            2        93.19
103  cb700ab2-64d2-4cdc-ba02-20c479f4e248            2        90.55
104  be64633f-627a-4539-925b-1f64337294c5            2        90.34
105  b5cc476d-1016-4690-998d-83b141c90244            2        88.75
106  6469eb2d-f0ca-4d12-a73a-23fbef42ff77            2        85.51
107  b7dc9ecd-5b00-468f-bd66-5515c1477866            2        81.44
108  f9883434-0bce-4ac9-8df8-31bc31fa5c17            2        79.43
109  fb33eda4-902f-47ab-a44e-670d3d0fb6ca            2        79.36
110  5955b61c-ce20-442c-a70a-bffe5dd06dd4            2        78.15
111  0c86e437-806f-4409-b0ba-d2d0b89d34da            2        77.22
112  009dd6c6-a577-4e67-86e3-282903230157            2        76.32
113  b33c8eba-7916-4b94-a08e-a98b0e41d77d            2        75.42
114  c30e5a9d-6b74-46ac-a71e-ec3f98c0749f            2        74.02
115  9fee121d-40e5-4e77-8614-cfd0816777fe            2        73.94
116  042edb3f-1326-4845-acbe-e679cc7785e2            2        73.15
117  223e0a57-10e5-4c64-85e2-8c6af603adda            2        72.67
118  f9291110-3b0d-4de5-8787-28ac48265b01            2        71.37
119  acb3f73e-1d5c-44a1-9b7f-fd31aaf4a725            2        70.02
120  0eea9ea7-70d3-4e92-b8c1-d68dbf28b6e8            2        69.92
121  630643a9-fe53-4c50-9faf-33252e13e4f1            2        66.98
122  748e9583-0251-44b0-8aaf-cf86702d3804            2        66.11
123  4dc58411-b070-4527-994f-88500f5e6438            2        64.68
124  e62d5b87-6f07-448a-a5ac-b62473120f29            2        63.58
125  ca7b4adc-7ae3-44a2-a075-3c2864b53ebc            2        63.22
126  79e80329-b47b-4c71-a756-febf0748d997            2        62.88
127  d443d28e-5069-4046-bb70-4b826c964110            2        60.12
128  782adef8-91c7-4a5f-a552-3bfe0eb5486e            2        60.10
129  09c0b606-6af2-440e-b090-aafdf7979e14            2        58.89
130  06e483e6-2cb6-4d69-8f6c-50f849e30c92            2        58.68
131  fd880873-0253-460c-9453-dda4cb79a013            2        57.83
132  36eca0bf-c90f-4db6-956f-47c49e16df16            2        57.14
133  05d55643-256a-4e53-af9f-28f0150c57d2            2        56.05
134  91c870c7-9479-4980-b235-814b9015c4f5            2        54.07
135  49a1e514-d845-4f09-ae15-d89f78865b28            2        52.01
136  3a05d865-3c2b-4c53-a70b-0f5587f0794f            2        48.41
137  afa87701-99ff-4b9f-bb5c-7c4015e56e3c            2        45.46
138  17142a5a-52c9-4d7e-b9e8-941f712bceef            2        44.44
139  6ed3a44b-e0f0-497e-895c-6cd833e92c61            2        43.01
140  b37f1c38-a899-4b12-a96c-e5795937ebae            2        36.70
141  8e10c439-7275-4ecf-9433-a8fa8b25c443            2        34.16
142  64addb4e-20a4-497c-83e1-42cb78f9e739            2        34.08
143  afad1960-4363-4a89-afa0-cfe5d239f3a0            2        22.85
144  e240637e-5444-4240-8ed7-ab68f2fef51b            2        20.87
145  90b79d45-b5ae-4c3c-b7f6-300eb65773c7            2        18.47

##Classify customers by purchase frequency

In [26]:
q="""
 WITH customer_orders AS (
    SELECT
        user_id,
        COUNT(DISTINCT order_id) AS order_count,
        SUM(total_amount) AS total_spent
    FROM purchases
    GROUP BY user_id
)
SELECT
    CASE
        WHEN order_count = 1 THEN 'One-time customer'
        WHEN order_count BETWEEN 2 AND 4 THEN 'Occasional customer'
        WHEN order_count BETWEEN 5 AND 9 THEN 'Frequent customer'
        ELSE 'Very frequent customer'
    END AS customer_segment,
    COUNT(*) AS customers,
    ROUND(AVG(total_spent), 2) AS avg_customer_spend
FROM customer_orders
GROUP BY 1
ORDER BY customers DESC;
"""
df=pd.read_sql(q,conn)
df

C:\Users\hp\AppData\Local\Temp\ipykernel_24468\3102013749.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(q,conn)

      customer_segment  customers  avg_customer_spend
0    One-time customer       1141               92.17
1  Occasional customer        146              166.74

##Best-selling products

In [28]:
q="""
 SELECT
    pr.product_id,
    pr.product_name,
    pr.category,
    pr.brand,
    SUM(p.quantity) AS units_sold,
    ROUND(SUM(p.total_amount), 2) AS revenue,
    COUNT(DISTINCT p.order_id) AS orders
FROM products pr
JOIN purchases p
    ON pr.product_id = p.product_id
GROUP BY
    pr.product_id, pr.product_name, pr.category, pr.brand
ORDER BY units_sold DESC
LIMIT 20;
"""
df=pd.read_sql(q,conn)
df

C:\Users\hp\AppData\Local\Temp\ipykernel_24468\1185858838.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(q,conn)

,product_id,product_name,category,brand,units_sold,revenue,orders
0,6e9b539a-77ad-4307-acb5-f558f8b5cc6f,Apple Accessorie Stand,Electronics,Apple,88.0,6140.92,84
1,c1ab2206-9b50-4aaa-9446-f322d0976ea6,The Data Structures: A Comprehensive Guide,Books,Simon & Schuster,84.0,1669.20,43
2,dbe68f3f-99a8-4ef2-a103-908a6fca244d,Wilson Fitness Equipment Pro,Sports & Outdoors,Wilson,71.0,3471.85,55
3,26fa0037-c745-4789-8a44-9f3dfb7f25f7,General Mills Organic Snack,Grocery & Gourmet,General Mills,59.0,1087.82,28
4,5d07bcd4-3670-4a0d-91f6-e36d7d335597,Adidas Sterling Silver Jewelry,Clothing & Accessories,Adidas,56.0,1524.11,40
5,88f38eae-9124-4557-a285-248fc1cad30c,Nestle Pantry Staple Multipack,Grocery & Gourmet,Nestle,56.0,433.08,32
6,58fd8edb-60ef-4856-bf1f-644ffc133d12,Wilson Book19 Fitness Equipment,Sports & Outdoors,Wilson,55.0,5883.08,41
7,eaaf2b74-b09a-4bf5-b0b2-09021044cab8,Instant Pot Microfiber Kitchenware,Home & Kitchen,Instant Pot,55.0,5218.45,41
8,c2e39751-db17-424f-8d71-61ec7ecad424,Neutrogena Bath & Body Lotion,Beauty & Personal Care,Neutrogena,54.0,1818.69,37
9,d3701c21-709a-4090-bab2-020261ce8a92,Cuisinart Smart Appliance,Home & Kitchen,Cuisinart,53.0,2363.42,41
10,1660a6f2-7ef5-4f47-a4aa-e917f41e014e,Tommy Hilfiger Womenswear Dress,Clothing & Accessories,Tommy Hilfiger,44.0,2503.33,37
11,25a6c99c-d63c-4697-91ef-744b7879d605,Post-it Premium Stationery Set,Office Products,Post-it,42.0,1926.20,34
12,341db25d-1cfb-4b01-8303-070a169d0c56,Legends - Volume 10,Books,Penguin Books,39.0,1708.83,27
13,8b875a73-88df-44ff-966d-5649d7a14d31,Nike Womenswear in Olive,Clothing & Accessories,Nike,34.0,2170.90,27
14,854f59a0-38d4-4e20-b346-43eca5ccb8cb,Nike Classic Accessorie,Clothing & Accessories,Nike,33.0,815.74,23
15,2e1a3d22-2a05-4b6e-bfd8-4b5d5dab3009,Michelin Heavy-Duty Car Accessorie,Automotive,Michelin,33.0,1325.89,29
16,111606d4-51dd-4751-b620-03fca7a12881,Neutrogena Drift Perfume Spray,Beauty & Personal Care,Neutrogena,29.0,481.56,22
17,bbc99c6e-1552-4677-8a8f-61a2e541e6c8,Apple Book4 Ultrabook,Electronics,Apple,28.0,7202.93,28
18,6651c3ab-c7be-4131-b324-68bd0218eb2c,Timberland Camping Gear Kit,Sports & Outdoors,Timberland,26.0,1795.58,19
19,920b6f6f-d113-4b7a-861b-b6bda3de9fdc,Professional Entrepreneurship: The Advanced Co...,Books,Penguin Books,25.0,489.07,14

##Products generating the most revenue

In [30]:
q="""
SELECT
    pr.product_id,
    pr.product_name,
    pr.category,
    pr.brand,
    SUM(p.quantity) AS units_sold,
    ROUND(SUM(p.total_amount), 2) AS total_revenue
FROM products pr
JOIN purchases p
    ON pr.product_id = p.product_id
GROUP BY
    pr.product_id, pr.product_name, pr.category, pr.brand
ORDER BY total_revenue DESC
LIMIT 20;
"""
df=pd.read_sql(q,conn)
df

C:\Users\hp\AppData\Local\Temp\ipykernel_24468\292026941.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(q,conn)

,product_id,product_name,category,brand,units_sold,total_revenue
0,bbc99c6e-1552-4677-8a8f-61a2e541e6c8,Apple Book4 Ultrabook,Electronics,Apple,28.0,7202.93
1,6e9b539a-77ad-4307-acb5-f558f8b5cc6f,Apple Accessorie Stand,Electronics,Apple,88.0,6140.92
2,58fd8edb-60ef-4856-bf1f-644ffc133d12,Wilson Book19 Fitness Equipment,Sports & Outdoors,Wilson,55.0,5883.08
3,eaaf2b74-b09a-4bf5-b0b2-09021044cab8,Instant Pot Microfiber Kitchenware,Home & Kitchen,Instant Pot,55.0,5218.45
4,dbe68f3f-99a8-4ef2-a103-908a6fca244d,Wilson Fitness Equipment Pro,Sports & Outdoors,Wilson,71.0,3471.85
5,f81e1fd5-a01b-4fbe-81d6-5dc5ab19b03c,Castrol Prime7 Electronic,Automotive,Castrol,23.0,2791.99
6,1660a6f2-7ef5-4f47-a4aa-e917f41e014e,Tommy Hilfiger Womenswear Dress,Clothing & Accessories,Tommy Hilfiger,44.0,2503.33
7,d3701c21-709a-4090-bab2-020261ce8a92,Cuisinart Smart Appliance,Home & Kitchen,Cuisinart,53.0,2363.42
8,4b9c83ae-69fe-4826-ac62-bae53913ea33,Apple Accessorie Stand,Electronics,Apple,8.0,2318.48
9,8b875a73-88df-44ff-966d-5649d7a14d31,Nike Womenswear in Olive,Clothing & Accessories,Nike,34.0,2170.90
10,02287feb-fd4c-46db-bba2-c8fbd0059fe9,Apple Ultra Prime3,Electronics,Apple,4.0,2146.77
11,684ddd4e-85c7-4969-8e1e-224a92f777c2,Samsung Pixel1 Smartphone,Electronics,Samsung,6.0,1995.03
12,fc8ff5d6-2425-45fd-9562-7e24de9f7cd1,Michelin Tools & Equipment Kit,Automotive,Michelin,16.0,1977.11
13,25a6c99c-d63c-4697-91ef-744b7879d605,Post-it Premium Stationery Set,Office Products,Post-it,42.0,1926.20
14,db62d281-8a73-4fbb-96fb-28cf2ba7a970,KitchenAid Comfort Bedding,Home & Kitchen,KitchenAid,6.0,1921.95
15,c2e39751-db17-424f-8d71-61ec7ecad424,Neutrogena Bath & Body Lotion,Beauty & Personal Care,Neutrogena,54.0,1818.69
16,d70d14b8-4566-4d3d-b9b3-eee857b374c0,Samsung X9 Fitness Tracker,Electronics,Samsung,7.0,1803.13
17,6651c3ab-c7be-4131-b324-68bd0218eb2c,Timberland Camping Gear Kit,Sports & Outdoors,Timberland,26.0,1795.58
18,341db25d-1cfb-4b01-8303-070a169d0c56,Legends - Volume 10,Books,Penguin Books,39.0,1708.83
19,c1ab2206-9b50-4aaa-9446-f322d0976ea6,The Data Structures: A Comprehensive Guide,Books,Simon & Schuster,84.0,1669.20

##Revenue by category and subcategory

In [32]:
q="""
SELECT
    pr.category,
    pr.subcategory,
    COUNT(DISTINCT pr.product_id) AS products_sold,
    SUM(p.quantity) AS units_sold,
    COUNT(DISTINCT p.order_id) AS orders,
    ROUND(SUM(p.total_amount), 2) AS revenue
FROM products pr
JOIN purchases p
    ON pr.product_id = p.product_id
GROUP BY pr.category, pr.subcategory
ORDER BY revenue DESC;
"""
df=pd.read_sql(q,conn)
df

C:\Users\hp\AppData\Local\Temp\ipykernel_24468\2967607581.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(q,conn)

,category,subcategory,products_sold,units_sold,orders,revenue
0,Sports & Outdoors,Fitness Equipment,14,154.0,116,10909.04
1,Electronics,Laptops,14,51.0,50,10685.59
2,Electronics,Accessories,7,105.0,99,9188.91
3,Electronics,Smartphones,18,44.0,41,8824.83
4,Home & Kitchen,Kitchenware,13,114.0,85,7761.84
5,Clothing & Accessories,Womenswear,15,110.0,84,6005.94
6,Electronics,Headphones,11,26.0,25,4700.76
7,Sports & Outdoors,Camping Gear,10,65.0,44,4438.30
8,Clothing & Accessories,Menswear,22,98.0,65,4194.21
9,Automotive,Tools & Equipment,8,57.0,45,3893.62
10,Electronics,Wearables,11,26.0,24,3767.97
11,Home & Kitchen,Appliances,8,89.0,70,3761.46
12,Books,Non-Fiction,10,150.0,77,3688.49
13,Automotive,Electronics,6,49.0,38,3468.85
14,Home & Kitchen,Bedding,11,24.0,16,2690.47
15,Office Products,Stationery,6,64.0,50,2550.44
16,Office Products,Office Furniture,5,39.0,28,2521.58
17,Sports & Outdoors,Team Sports,9,28.0,20,2394.62
18,Clothing & Accessories,Accessories,10,74.0,54,2051.04
19,Beauty & Personal Care,Bath & Body,6,63.0,44,2043.18
20,Clothing & Accessories,Jewelry,7,65.0,46,1833.60
21,Electronics,Cameras,5,9.0,9,1759.33
22,Books,Comics,2,40.0,28,1745.40
23,Sports & Outdoors,Cycling,9,37.0,26,1733.68
24,Toys & Games,Puzzles,7,28.0,25,1654.21
25,Automotive,Car Accessories,6,39.0,34,1564.54
26,Home & Kitchen,Home Decor,9,41.0,33,1542.45
27,Sports & Outdoors,Outdoor Recreation,13,21.0,19,1524.88
28,Beauty & Personal Care,Fragrance,8,59.0,45,1508.97
29,Home & Kitchen,Furniture,12,29.0,20,1440.63
30,Electronics,Tablets,6,8.0,8,1389.03
31,Grocery & Gourmet,Snacks,9,78.0,40,1310.20
32,Automotive,Car Care,5,12.0,9,1296.13
33,Books,Fiction,9,38.0,23,1013.76
34,Clothing & Accessories,Footwear,13,40.0,27,919.46
35,Beauty & Personal Care,Haircare,9,28.0,21,860.30
36,Toys & Games,Video Games,6,19.0,16,777.42
37,Toys & Games,Action Figures,7,40.0,33,697.41
38,Toys & Games,Board Games,10,16.0,13,665.55
39,Grocery & Gourmet,Pantry Staples,7,85.0,47,615.59
40,Beauty & Personal Care,Makeup,5,28.0,24,584.97
41,Beauty & Personal Care,Skincare,7,19.0,17,573.97
42,Home & Kitchen,Lighting,8,12.0,10,516.03
43,Toys & Games,Educational Toys,5,15.0,9,497.81
44,Automotive,Fluids,3,4.0,3,433.81
45,Books,Children's Books,6,21.0,11,386.12
46,Office Products,Printers,3,11.0,7,295.37
47,Office Products,Organization,2,11.0,6,242.49
48,Clothing & Accessories,Bags,3,5.0,5,198.43
49,Grocery & Gourmet,Beverages,4,27.0,10,169.52
50,Grocery & Gourmet,Organic Foods,5,19.0,9,159.45
51,Books,Educational,1,3.0,2,30.78
52,Office Products,Supplies,2,2.0,2,28.42

##Find products with no sales

In [33]:
q="""
SELECT
    pr.product_id,
    pr.product_name,
    pr.category,
    pr.price,
    pr.stock_quantity,
    pr.date_added
FROM products pr
LEFT JOIN purchases p
    ON pr.product_id = p.product_id
WHERE p.purchase_id IS NULL
ORDER BY pr.date_added DESC;
"""
df=pd.read_sql(q,conn)
df

C:\Users\hp\AppData\Local\Temp\ipykernel_24468\3992669512.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(q,conn)

,product_id,product_name,category,price,stock_quantity,date_added
0,5421da2a-4a0c-437d-934d-d2384fae9de4,The Meditation: The Definitive Guide,Books,8.37,1,2026-05-27
1,5d4ad04e-36bd-4988-a98d-d34720e44811,"LEGO Jack 27"" Figure",Toys & Games,8.21,3,2026-05-22
2,9256e0fe-5645-4196-a875-26b97940487e,Coleman Premium Fitness Equipment,Sports & Outdoors,37.82,2,2026-05-22
3,196e5f63-122c-4d20-abee-9b92d298b5e5,Nike Premium Womenswear,Clothing & Accessories,19.85,3,2026-05-19
4,4f9e7267-cd6f-42ec-916d-7bb0957a5f19,Apple Essential Sport Watch,Electronics,23.90,2,2026-05-11
5,85016e04-8cd0-47e3-8b77-52d6de00cfcf,Nike Premium Menswear,Clothing & Accessories,40.39,3,2026-05-05
6,c3f78b59-fd61-4c40-91f2-a5ae1e894b43,Wilson Outdoor Recreation Set,Sports & Outdoors,39.25,2,2026-05-03
7,2758ff6a-d2a3-43d0-ba31-3b52bebcbe2a,Olay Bath & Body Scrub,Beauty & Personal Care,18.27,1,2026-04-29
8,520cf0b3-8fe9-42ba-a245-f42e60a656d9,Wilson Edge13 Camping Gear,Sports & Outdoors,29.52,8,2026-04-29
9,776df9ea-e13e-40b6-bb01-fa51110f4390,A premium legacy,Books,20.53,2,2026-04-24
10,ec87a594-19d2-497a-9156-fb77b3658b7e,The North Face Classic Sandals,Clothing & Accessories,41.56,1,2026-04-24
11,fb87061e-fc17-4219-9702-c463c7439bcf,Wilson 118L Camping Gear,Sports & Outdoors,30.09,2,2026-04-17
12,c9ee4eea-8bb8-44eb-a334-3b997749602a,Staples Assorted Stationery,Office Products,9.33,2,2026-04-15
13,db090e5d-82e1-4bfe-83ba-09e2ee97e409,Samsung Core Smartwatch,Electronics,228.41,1,2026-04-15
14,216381f0-a419-4518-ae02-b0c5f385c0e3,Maybelline Aura Perfume Spray,Beauty & Personal Care,14.09,2,2026-04-12
15,d5beeaa2-6999-4a44-9edf-f299efab2d46,L'Oreal Haircare Shampoo,Beauty & Personal Care,12.73,1,2026-04-10
16,51d0e076-b71f-4770-8790-2f4285e33420,Nike Silver Jewelry,Clothing & Accessories,12.15,1,2026-04-09
17,caf04ff6-0545-4ee0-8753-619458dedc5f,KitchenAid Comfort Bedding,Home & Kitchen,56.04,3,2026-04-08
18,895004bb-bc48-4955-95ba-fcbc9c59fbe5,Elegant of silence,Books,12.55,12,2026-04-06
19,eb9909fa-f529-44d6-a27d-94305e2ba604,Pyrex Cotton Home Decor,Home & Kitchen,25.11,1,2026-04-01
20,f74aad66-b598-429e-9839-b3e0ee95d2ee,Dell Book13 Bluetooth Earbuds,Electronics,93.54,2,2026-03-31
21,132eb790-dc8b-4955-9ebd-d07c2c5d492c,LEGO Pro Deluxe Leo,Toys & Games,32.04,1,2026-03-29
22,db058a09-6fbc-4923-8eda-d73ec8d7511d,The World History: An Introduction for Beginners,Books,10.83,5,2026-03-29
23,aa68015e-8f26-4199-821f-4db8434ce3df,Sony Prime 5th Gen,Electronics,222.25,1,2026-03-28
24,5e8855cc-835f-493f-8e5c-38c61cc98cbc,Nike Premium Accessorie,Clothing & Accessories,39.35,1,2026-03-23
25,1d4f54e4-16a4-4d27-a651-2abf2087e42d,Linear Algebra: A compact History,Books,15.08,1,2026-03-22
26,cf3c6032-d25f-42cb-8dbf-951141d60bd9,Bosch Car Care Cleaner,Automotive,30.72,11,2026-03-22
27,44fb591e-8de0-4541-b160-90464edb9122,KitchenAid Professional Kitchenware,Home & Kitchen,52.15,1,2026-03-19
28,1d4e8909-0873-43a1-87f9-c968b439d6e1,Apple Accessorie Adapter,Electronics,164.58,1,2026-03-17
29,e9a74e71-3e0f-4f0b-a67e-c035fa4cb966,Apple Pro13 Pro 5G,Electronics,202.07,2,2026-03-15
30,f65940dc-1f9b-4034-9ace-5b480ad6c9f9,3M Printer Pro,Office Products,17.86,2,2026-03-14
31,ca57c0e0-2846-47a3-83eb-6b1f5542361f,Mattel Max Action Figure,Toys & Games,52.57,1,2026-03-13
32,f889873f-297b-4fd9-b608-8e123c00483a,Fisher-Price Panoramic Machine Learning Puzzle,Toys & Games,31.46,3,2026-03-10
33,0086bdef-729f-4a6a-b636-09655dd15052,L'Oreal Makeup Palette,Beauty & Personal Care,13.63,1,2026-03-02
34,38b30516-4eba-43d9-a44b-e372e609bc27,"KitchenAid 14"" Kitchenware Set",Home & Kitchen,23.16,1,2026-02-26
35,b1ae4b31-7866-444a-8d59-c3310d967d7d,LEGO Jack Collectible,Toys & Games,33.64,2,2026-02-26
36,413730d7-8b68-45d7-a4b2-a7da580339a3,Nike Classic Fit Menswear,Clothing & Accessories,33.90,11,2026-02-25
37,7972c35d-80be-48e8-bd9f-bc7eb80120b3,Brother Desktop Organization,Office Products,37.70,1,2026-02-20
38,938c5e12-892a-4b77-afea-8ff809f98366,Apple Ultra Series11,Electronics,534.27,1,2026-02-19
39,9a4c5e8a-5831-4b7f-8a36-28150eeea59e,Apex and the professional apex,Books,9.73,41,2026-02-19
40,e9057e4c-5b85-426f-a6d9-28f830530cfe,L'Oreal Haircare Serum,Beauty & Personal Care,11.95,1,2026-02-17
41,72ce0593-0728-44df-a455-40bfeed0dd56,Cuisinart Decorative Home Decor,Home & Kitchen,26.29,4,2026-02-11
42,825d03b5-2982-4c8c-9403-4bd456ba7cb4,Le Creuset Cotton Home Decor,Home & Kitchen,12.36,2,2026-02-11
43,f6458376-2889-4221-b909-bdaf4cccc779,Wilson 55L Camping Gear,Sports & Outdoors,116.80,1,2026-02-11
44,233d8a06-84c1-4fd8-a3b2-34bbce6e2385,Sony Prime X8,Electronics,367.78,1,2026-02-07
45,b039719b-51c0-4f5c-8469-aef5a0397016,Apple Essential Tablet,Electronics,188.04,1,2026-02-04
46,6c02f0ce-2183-4d32-a907-bb033c961fe9,Apple Galaxy5 Pro 5G,Electronics,54.89,1,2026-02-03
47,e6c597ce-cd80-4439-ab5e-bdb9fdc77149,Pyrex Modern Furniture,Home & Kitchen,40.82,5,2026-02-03
48,8a647bd2-f66f-469b-874d-01a1358c55f0,L'Oreal Skincare Complex,Beauty & Personal Care,27.21,2,2026-01-28
49,4e0b8bd9-5f80-4c70-9fdb-d848885e8805,KitchenAid Smart Appliance,Home & Kitchen,13.77,1,2026-01-23
50,b6ccd093-e5fa-415b-bac9-adaa6a8e9e68,L'Oreal Matte Makeup,Beauty & Personal Care,12.78,1,2026-01-23
51,311ea60f-b387-4466-b952-fcb212198afd,Apple Pixel1 Pro 5G,Electronics,208.97,5,2026-01-22
52,ff991311-edc8-4bd9-9e20-780f3cd9239d,Twinnings Non-GMO Organic Food,Grocery & Gourmet,14.12,7,2026-01-14
53,a8953964-4612-412d-981e-3002313ebf56,Adidas Galaxy12 Training Shoes,Clothing & Accessories,27.01,1,2026-01-13
54,8cbd67b3-730d-47e0-8306-63f6a4dd379c,Vortex and the sleek vortex,Books,27.65,3,2026-01-09
55,873c9039-bba6-4e4d-9248-4df04d539770,KitchenAid Professional Kitchenware,Home & Kitchen,74.28,1,2026-01-04
56,d3afa213-522c-4df6-9c51-b8cab15c0bdb,Apple Z5 Smartphone,Electronics,498.03,2,2026-01-04
57,6e4953ee-17bc-4f99-8c81-3d5f7815777c,Neutrogena Makeup Palette,Beauty & Personal Care,22.20,1,2026-01-02
58,7b8c373c-f7b7-42bf-9247-e6b6a1db27cd,LEGO 3D Haven Puzzle,Toys & Games,71.77,2,2026-01-02
59,55752af4-afb4-4154-a769-858b5cc94a85,LEGO Cascade STEM Kit,Toys & Games,23.86,2,2025-12-26
60,b2e4a88d-89ca-4afe-a050-eb9300e4aa95,Advanced Digital Marketing,Books,16.92,1,2025-12-26
61,14aa716c-9404-4b1e-90e3-9dfcfcc0033d,KitchenAid Ultra-Soft Bedding,Home & Kitchen,75.56,2,2025-12-25
62,2237ff96-b78a-409e-ba13-3b7af0463aed,Zara Menswear in Cream,Clothing & Accessories,152.02,1,2025-12-24
63,9edf3c2c-b903-4c32-8dc3-7a9011f5f868,Apple Z19 Bluetooth Earbuds,Electronics,410.23,1,2025-12-24
64,34a77a70-6a07-40d2-936d-df4647fea13d,Sony Accessorie Charger,Electronics,154.71,3,2025-12-19
65,e3baf771-a60d-4ac8-b619-25ff65a58ccb,Portable cipher Adventure,Books,15.08,2,2025-12-18
66,11d41a47-4a1c-47fd-8f21-ef734dbc0a88,Cuisinart Comfort Bedding,Home & Kitchen,127.68,6,2025-12-16
67,0fd8be61-bce2-480c-95b9-66e8e07e0a3c,Samsung Max Noise-Canceling Headphones,Electronics,178.98,1,2025-12-15
68,ec18ade1-b0a3-48c3-bc9f-de34fc29c34e,Samsung Air7 DSLR,Electronics,886.76,1,2025-12-15
69,8e7b93f6-32cc-413d-b73b-ad49a1db72d9,Leadership for Data Scientists,Books,7.16,10,2025-12-14
70,186f61dd-1b37-4d39-a253-3e93a2f57374,Le Creuset Modern Lighting,Home & Kitchen,43.94,1,2025-12-12
71,ee639333-59d9-4181-a33c-ee89896e11c0,JBL Pro Over-Ear Headphones,Electronics,263.85,22,2025-12-12
72,ff5a11ee-d83f-4539-9987-2267186fbfd8,Max: The Definitive Guide,Toys & Games,32.37,11,2025-12-11
73,4a56e17e-344c-4772-8201-8d2a699b8a61,KitchenAid Scandinavian Home Decor,Home & Kitchen,93.35,1,2025-12-08
74,87a25311-10b2-4d32-a0a0-895640929060,Tommy Hilfiger Essential Menswear,Clothing & Accessories,14.00,1,2025-12-05
75,51aaaec0-3190-4437-bd77-d17378d85bb0,Staples Adjustable Office Furniture,Office Products,24.20,2,2025-12-03
76,ede55b83-a7fa-4873-93aa-c69628714e2e,H&M Prime2 Training Shoes,Clothing & Accessories,44.28,1,2025-12-03
77,1f6ae9d8-56b8-4eda-91e5-ff53f5b97c52,Dyson Premium Cotton Bedding,Home & Kitchen,67.00,1,2025-12-02
78,3a90919f-9c1f-4717-9d32-44ae17fba3e5,L'Oreal Skincare Cream,Beauty & Personal Care,45.09,1,2025-12-01
79,2b5d618e-d4a1-4ea6-957f-2468c77092ab,Adidas Womenswear in Cream,Clothing & Accessories,14.40,3,2025-11-30
80,d83c016f-e125-4cb0-a533-6a94d809d429,Shark Fleece Furniture,Home & Kitchen,30.88,1,2025-11-29
81,ee9a7086-5d93-4c5b-a734-9e573667ca43,Zara Edge19 Running Shoes,Clothing & Accessories,9.21,14,2025-11-25
82,efc6dbc0-0c3b-459a-a0fd-334a554a9e69,Nike Air Sandals,Clothing & Accessories,23.04,1,2025-11-23
83,ea0afd71-a6f0-4e9c-b905-b62721bca09f,Cuisinart Furniture Set,Home & Kitchen,30.48,1,2025-11-21
84,7285a4a6-cea0-4f24-a032-be807939c072,Dove Elysium Eau de Parfum,Beauty & Personal Care,21.01,1,2025-11-16
85,1780b82e-2ba3-46f3-a6de-e3162c5e667b,HP Max9 Pro Tablet,Electronics,165.17,1,2025-11-11
86,9f4d0e2d-1af4-408d-95ff-f5f2c3dea6ef,Apple Galaxy11 Smartphone,Electronics,352.34,3,2025-11-08
87,577bc486-8da7-4aa4-ab2b-12bdb72ebeb0,Nike Premium Womenswear,Clothing & Accessories,131.11,1,2025-11-06
88,61a5683d-e524-45fa-8527-19526e9151cd,L'Oreal Bath & Body - Almond,Beauty & Personal Care,20.03,13,2025-11-02
89,04f4e6f5-8abc-4544-badb-a909ff3a2352,Zara Air1 Running Shoes,Clothing & Accessories,29.78,1,2025-10-30
90,5e875953-b164-41c5-91ad-a71f35ae5c8a,Apple Wireless Accessorie,Electronics,208.37,1,2025-10-29
91,dd43ead1-95e9-4d9b-bb57-e4fa75e92dcd,Nestle Non-GMO Organic Food,Grocery & Gourmet,10.17,2,2025-10-29
92,73a2d656-ffa8-458d-9fc2-d7489c59329f,Instant Pot Modern Furniture,Home & Kitchen,105.47,1,2025-10-28
93,1063bdf9-5119-4f27-bcdb-051b1a60eaf0,Apple Core Tab,Electronics,107.95,2,2025-10-27
94,a4407635-9c5c-4f35-b56b-c6e50a97d784,Samsung Max Action Cam,Electronics,80.11,1,2025-10-26
95,13107544-4733-4724-a29e-e291cba60ae1,Wilson Waterproof Camping Gear,Sports & Outdoors,35.59,2,2025-10-23
96,233ea18b-ca97-4371-ba51-51731e512c3a,Apple Prime Prime5,Electronics,175.72,2,2025-10-20
97,2068100b-794f-4e1b-8f91-6eaade53c5ff,H&M Core Tote Bag,Clothing & Accessories,30.66,1,2025-10-19
98,37b6fd84-d92c-4166-b883-bc70ec3078af,Samsung Prime5 Ultra,Electronics,103.14,1,2025-10-18
99,7b10c51f-7f57-4542-96cb-531815a363b1,Architecture: A superior History,Books,15.30,1,2025-10-14
100,2cb8afa1-906e-42c6-bc0f-a58557387ecf,Nike Max14 Running Shoes,Clothing & Accessories,54.32,6,2025-10-13
101,b60f1882-8ef5-4fc6-8cdd-97f657f65c7d,3M Organization Organizer,Office Products,10.69,2,2025-10-13
102,671ce81b-64a1-48d0-bf57-c234ece5bf72,Post-it Supplie Multipack,Office Products,7.69,1,2025-10-11
103,31e0fdcb-41e0-43c9-bbf4-c5c76daa33aa,Hasbro Core Deluxe Sam,Toys & Games,52.63,1,2025-10-10
104,355e61f8-67d0-4158-a39f-0d12f974eb60,LEGO Elite Jack Figure,Toys & Games,32.85,1,2025-10-06
105,b2dbae96-90ef-4212-b4ea-fd68ea6f4623,Nike Menswear in Brown,Clothing & Accessories,59.79,3,2025-09-28
106,99aee34b-3b16-4337-8132-f183349dfd69,Staples Organization Set,Office Products,13.45,2,2025-09-27
107,a1f07dad-ec9d-481a-97ef-d82cebdf6f96,KitchenAid Premium Kitchenware,Home & Kitchen,27.51,1,2025-09-27
108,e404770b-d18a-4932-ac69-cf474a5f714f,Puma Essential Menswear,Clothing & Accessories,68.81,4,2025-09-27
109,1e7c79d1-0a00-4d37-b3e1-2f6262900884,Samsung Accessorie Stand,Electronics,90.86,2,2025-09-26
110,09e6cda9-42a6-4d6e-8cd0-044feb4f97a0,"HP Studio 17""",Electronics,244.79,2,2025-09-23
111,82e46c00-73fc-4f52-8c42-59ea245bae9b,LEGO Velvet Building Set,Toys & Games,17.97,8,2025-09-22
112,b9dc6a95-b011-4e0a-9dab-ebfcbb201b73,Wilson Waterproof Camping Gear,Sports & Outdoors,31.47,2,2025-09-22
113,27312073-c823-4e6b-a74b-2ce328bd8ef5,Nike Menswear in Sage,Clothing & Accessories,78.86,1,2025-09-15
114,7692a311-2840-4e48-9f16-c3b47c9dc54d,KitchenAid Professional Kitchenware,Home & Kitchen,50.07,2,2025-09-12
115,8f95d984-6cee-479b-8b36-983a1913d771,Apple Accessorie Charger,Electronics,173.59,2,2025-09-12
116,f5b4f7f0-ad84-414d-b6a9-ec386fbd8a8d,Learn Fitness with Sam,Books,16.39,1,2025-09-10
117,f7a18d7b-7709-4f0c-8e17-a97e31fff475,Wilson Premium Outdoor Recreation,Sports & Outdoors,22.53,20,2025-09-08
118,c5e8201b-a5f7-4e18-8e08-f3ae3df053ba,"Dell Studio 32"" Display Tablet",Electronics,91.40,1,2025-09-06
119,6423c371-130e-481a-8f65-57c728cb6ae7,The Sleek Drift: A Practical Approach,Books,8.35,1,2025-09-05
120,7b74b088-3813-40c8-b3e0-22f3c72ee791,MAC Haircare Treatment,Beauty & Personal Care,12.82,1,2025-09-05
121,07c063a3-3e62-4e4b-9a3d-79c63ae26e68,Ninja Non-Stick Kitchenware,Home & Kitchen,33.87,1,2025-09-04
122,0bdf11b7-bd95-49ef-ab31-55c3ee721a30,Pyrex Smart Lighting,Home & Kitchen,74.28,1,2025-09-04
123,6a3c603e-d935-4280-8d4c-8a4b725fa8af,A robust drift,Books,20.14,1,2025-09-02
124,42a3fba8-01da-40a0-a1be-dfcb7b92ad33,Apple Classic Hybrid Smartwatch,Electronics,195.50,4,2025-09-01
125,f78b3d6a-36dd-4fda-8382-31865d961859,H&M Gold-Plated Jewelry,Clothing & Accessories,14.49,2,2025-09-01
126,fa6f0458-dc6f-4247-a498-617abb0bbc33,Compact Blockchain: The Principles and Applica...,Books,9.32,1,2025-08-30
127,5d1b02bb-80d1-4864-a481-dfc5678b4a54,LEGO Aura Family Game,Toys & Games,15.41,2,2025-08-29
128,1f666d27-8853-4949-87dc-4bd2ea44d7bb,KitchenAid Modern Furniture,Home & Kitchen,67.18,4,2025-08-27
129,22ce4a6c-3a8e-4c2e-a596-cf9d97a11b52,Puma Classic Duffel Bag,Clothing & Accessories,60.83,4,2025-08-26
130,2a5600e0-4c5c-4cfc-83b8-1ddc1b800877,HP Accessorie Charger,Electronics,161.61,10,2025-08-25
131,dafd112c-f226-40f8-a298-ed495d08874f,The innovative element,Books,16.99,13,2025-08-23
132,a3e2e317-2f8a-4dd5-9072-531b755f4d0d,"Nestle Pantry Staple - 32""",Grocery & Gourmet,6.46,13,2025-08-21
133,fa8e94c7-decb-44da-b86d-0ce73492874c,Digital Marketing for Data Scientists,Books,8.49,5,2025-08-19
134,c64a19bc-f692-4de2-9ae5-454cd9d84637,Bosch Professional Tools & Equipment,Automotive,12.24,2,2025-08-18
135,7eae57c1-c5f0-403f-94c2-adccd2e891d7,Wilson Max10 Team Sport,Sports & Outdoors,78.13,1,2025-08-16
136,e7234ca8-c931-4f65-8aaa-f628e9aabdae,Apple Air Over-Ear Headphones,Electronics,299.60,538,2025-08-09
137,0ae12b0d-c386-4668-9fef-676f4ab93216,Le Creuset Microfiber Kitchenware,Home & Kitchen,32.14,3,2025-08-07
138,2dbb93cb-25b0-4b5d-820d-3e8877237f50,LEGO Midnight Learning Set,Toys & Games,30.99,1,2025-08-05
139,82f9fd9d-6a36-4638-b5b7-20792e75f4a7,Bosch Fluid Mercedes MB 229.5,Automotive,54.61,2,2025-08-04
140,cc6547e1-7252-46bb-beac-f9a4a493dce0,Wilson Portable Outdoor Recreation,Sports & Outdoors,45.63,1,2025-07-28
141,ac5ba701-9bf1-4091-895b-f4be675b088d,Cuisinart Non-Stick Kitchenware,Home & Kitchen,23.71,4,2025-07-27
142,6c915719-e0e2-4c7c-a69c-398305b55a7a,The advanced Guide to Yoga,Books,14.22,2,2025-07-26
143,cbb3e5bc-c8cd-4ad5-a4c3-4fd732148c36,Maybelline Aura Perfume Spray,Beauty & Personal Care,51.11,2,2025-07-22
144,d74b2d27-83c9-4d3b-b650-ff3f91f9e1e7,Advanced Optimization,Books,11.98,3,2025-07-22
145,37c91f3d-72e5-4f4d-b001-07af34335aa1,The modern Philosophy Handbook,Books,25.46,1,2025-07-19
146,3ebaae94-fb58-4115-bc3b-f28591c099ef,Introduction to Software Engineering,Books,13.98,2,2025-07-18
147,593b5a60-ad0f-43fa-b1e7-8a97f23a6475,Samsung Book1 Instant Camera,Electronics,114.97,1,2025-07-17
148,c0bb4ff1-d539-4103-85e3-00090887c8cb,Apple Max11 Pro Tablet,Electronics,198.10,39,2025-07-16
149,f84f1975-c50d-4044-9b8a-a4c36cf11bf8,Sony Air1 Pro 5G,Electronics,242.06,2,2025-07-16
150,6582625f-3f3e-4e8d-9df3-b5f539f52c35,Hot Wheels Aura Science Experiment,Toys & Games,20.58,3,2025-07-15
151,e6838a70-dd74-4cab-97a6-88a7cec29978,Samsung Air Smartwatch,Electronics,140.36,1,2025-07-15
152,74073ef0-27ce-4323-a134-ae96c9cd6dca,KitchenAid Ultra-Soft Bedding,Home & Kitchen,42.83,5,2025-07-10
153,825d7643-2038-4cc7-b412-da428d1d86b7,Cuisinart Comfort Bedding,Home & Kitchen,24.89,1,2025-07-10
154,00e04a62-b9a6-4bd4-ad1e-fc5ec979e5b5,Bowflex Adjustable Fitness Equipment,Sports & Outdoors,82.24,1,2025-07-09
155,4e5c9477-fa55-41c8-98fe-a01014cb2d15,Compact Leadership: The Advanced Concepts Expl...,Books,13.82,2,2025-07-08
156,e8748b29-4c82-432c-a088-3f0b612eb7d2,Yeti Portable Outdoor Recreation,Sports & Outdoors,41.28,1,2025-07-02
157,42f60e55-58f2-4129-a7b0-cb4ec5753faf,"Odyssey #7: Concepts, Techniques, and Tools",Books,9.20,1,2025-07-01
158,ba2e26b1-16e7-4b86-9e48-ab24dc3c26ff,Nike Menswear in Sand,Clothing & Accessories,38.78,1,2025-06-30
159,eb1b7a62-c765-4d68-8df2-9b0210e90d9a,Staples Compact Office Furniture,Office Products,23.28,12,2025-06-30
160,b0198cad-0f24-44c7-90c5-88c2a4d7d331,Philips Air18 Fitness Tracker,Electronics,53.71,2,2025-06-28
161,fb75d679-90cd-4a77-950c-e5ad2f32cb85,Minecraft Max Aria Figure,Toys & Games,21.23,1,2025-06-28
162,897fbea8-369d-45b9-a88e-61d89b7745b5,Introduction to Software Engineering,Books,11.23,1,2025-06-26
163,d834d935-3177-4efa-8508-effcc38d8c60,The robust Guide to Reinforcement Learning,Books,23.93,17,2025-06-26
164,48824001-8422-4fb7-a988-a9d8447e81f3,Lenovo Air16 DSLR,Electronics,572.66,1,2025-06-25
165,e218ae73-e52b-41cd-be42-73a06f169fe4,The elegant vertex,Books,9.33,2,2025-06-25
166,e5e214ce-88aa-4332-93bb-93297fee34c7,Timberland Ultralight Camping Gear,Sports & Outdoors,24.86,3,2025-06-25
167,19a76693-4727-45ef-9277-18819845b777,Apple Edge18 Pro 5G,Electronics,243.94,2048,2025-06-22
168,232c35ad-ed2e-4a01-a68c-6e9234063892,Nike Pixel14 Backpack,Clothing & Accessories,79.68,9,2025-06-21
169,8ebe35c7-f797-452c-8871-ffd6c856e8e3,Advanced NLP,Books,4.31,1,2025-06-21
170,34421bc0-cc97-4807-a0a7-5ad759d87c65,Le Creuset Rustic Lighting,Home & Kitchen,68.82,1,2025-06-20
171,d2442dc1-0962-4c45-9fd4-dc21eb729c85,Nike Essential Womenswear,Clothing & Accessories,110.02,1,2025-06-18
172,732c859a-2ab4-400c-a207-ab515f6d6123,Nike Sterling Silver Jewelry,Clothing & Accessories,47.91,1,2025-06-11
173,a98c5dcd-10b5-4d25-aec0-9a632c7dff45,Apple Edge14 Pro 5G,Electronics,510.54,2,2025-06-10
174,7d73f5a0-9d24-4e15-8bba-eac1995a726a,Zara Prime1 Hiking Boots,Clothing & Accessories,43.72,2,2025-06-04
175,9a59e2a6-3c12-48dd-8b90-f79fc161e7f2,Dove Bath & Body Wash,Beauty & Personal Care,10.99,1,2025-06-01
176,0cae6b2b-a5f9-43e7-8349-92ad987901ec,Apple Pro8 Bluetooth Earbuds,Electronics,187.90,8,2025-05-30
177,7dd2f487-d433-4185-99db-0e084dee1882,Learn Programming with Ella,Books,13.27,1,2025-05-30
178,277bceef-c970-496f-bac5-e3465630acfe,L'Oreal Midnight Perfume Spray,Beauty & Personal Care,20.79,2,2025-05-27
179,fa6a90c7-9768-4283-8a77-45ef0849d76e,LEGO Leo Action Figure,Toys & Games,22.37,1,2025-05-21
180,38a52dba-365b-4c3e-a80d-bd32ca1d5319,Apple Edge4 Digital Camera,Electronics,468.78,1,2025-05-18
181,dd7f06d5-acb6-41c9-9283-04f6b571c4e9,Blockchain for Young Learners,Books,15.10,1,2025-05-17
182,6efab8db-f0a2-4fd3-acb9-d94610c2b4a1,Spalding Z15 Cycling,Sports & Outdoors,49.61,1248,2025-05-16
183,a9734f27-7936-421c-9ca3-cdb4881ac29e,ASUS Z3 Ultra,Electronics,217.62,1,2025-05-16
184,91a9f312-e0c0-4ecb-afba-5ba640b7b615,Gap X11 Running Shoes,Clothing & Accessories,42.60,2,2025-05-15
185,b1ecb01d-c9e6-4384-a51e-3478f1b9e050,A Ultimate Aurora - Xbox Series X Edition,Toys & Games,22.47,7,2025-05-15
186,c6a70e79-cfac-45c0-9dcc-8e9525948be1,Cuisinart Digital Appliance,Home & Kitchen,167.56,1,2025-05-15
187,29015888-2b89-4204-8244-ba4d3257caec,A Sophisticated Aurora,Books,6.76,1,2025-05-12
188,dec11364-d0a9-4dff-8cca-4e0bb74013e1,"Nestle Gourmet Food - 14""",Grocery & Gourmet,5.81,1,2025-05-06
189,936fb559-2a18-4d8d-8267-ac5e006a1a52,Clinique Makeup Foundation,Beauty & Personal Care,10.13,21,2025-05-02
190,3cbd966b-3ec3-493c-b9a1-d8f59886b546,Apple Essential Edge5 Laptop,Electronics,565.33,2,2025-04-30
191,4162fcbc-cae2-42c8-89ad-7e8ba8854f1c,Turtle Wax Synthetic Fluid,Automotive,17.58,3,2025-04-27
192,72af798d-dd65-4dfe-b807-d84757d3e847,A Superior Spectrum: Building Real-World Solut...,Books,12.35,5,2025-04-27
193,599afd9a-72f9-4f7e-b325-6f795e3d220e,Nike Accessorie - Sage,Clothing & Accessories,69.04,1,2025-04-26
194,23f5d0e7-9ced-4641-a343-cbfd288da0ef,"Cuisinart 15.6"" Kitchenware Set",Home & Kitchen,48.84,1,2025-04-20
195,78c15786-9013-4add-8b7d-2939a24ffebe,Entrepreneurship: A advanced History,Books,5.64,10,2025-04-19

##Analyze customer engagement by product

In [35]:
q="""
SELECT
    pr.product_id,
    pr.product_name,
    pr.category,
    COUNT(i.interaction_id) AS total_interactions,
    COUNT(DISTINCT i.user_id) AS unique_users,
    ROUND(AVG(i.dwell_time_ms), 2) AS avg_dwell_time_ms
FROM products pr
JOIN interactions i
    ON pr.product_id = i.product_id
GROUP BY
    pr.product_id, pr.product_name, pr.category
ORDER BY total_interactions DESC
LIMIT 20;
"""
df=pd.read_sql(q,conn)
df

C:\Users\hp\AppData\Local\Temp\ipykernel_24468\3397766062.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql(q,conn)

,product_id,product_name,category,total_interactions,unique_users,avg_dwell_time_ms
0,6e9b539a-77ad-4307-acb5-f558f8b5cc6f,Apple Accessorie Stand,Electronics,6777,1557,17935.92
1,c1ab2206-9b50-4aaa-9446-f322d0976ea6,The Data Structures: A Comprehensive Guide,Books,3807,1088,18149.28
2,eaaf2b74-b09a-4bf5-b0b2-09021044cab8,Instant Pot Microfiber Kitchenware,Home & Kitchen,3359,1002,17108.04
3,58fd8edb-60ef-4856-bf1f-644ffc133d12,Wilson Book19 Fitness Equipment,Sports & Outdoors,3206,936,17785.97
4,1660a6f2-7ef5-4f47-a4aa-e917f41e014e,Tommy Hilfiger Womenswear Dress,Clothing & Accessories,2935,988,17735.21
5,2e1a3d22-2a05-4b6e-bfd8-4b5d5dab3009,Michelin Heavy-Duty Car Accessorie,Automotive,2599,829,17840.25
6,25a6c99c-d63c-4697-91ef-744b7879d605,Post-it Premium Stationery Set,Office Products,2586,638,18069.40
7,dbe68f3f-99a8-4ef2-a103-908a6fca244d,Wilson Fitness Equipment Pro,Sports & Outdoors,2488,831,17111.98
8,c2e39751-db17-424f-8d71-61ec7ecad424,Neutrogena Bath & Body Lotion,Beauty & Personal Care,2232,819,17328.76
9,d3701c21-709a-4090-bab2-020261ce8a92,Cuisinart Smart Appliance,Home & Kitchen,2113,788,18171.94
10,88f38eae-9124-4557-a285-248fc1cad30c,Nestle Pantry Staple Multipack,Grocery & Gourmet,2107,580,18224.95
11,26fa0037-c745-4789-8a44-9f3dfb7f25f7,General Mills Organic Snack,Grocery & Gourmet,2042,1124,17598.66
12,5d07bcd4-3670-4a0d-91f6-e36d7d335597,Adidas Sterling Silver Jewelry,Clothing & Accessories,1916,832,18156.08
13,341db25d-1cfb-4b01-8303-070a169d0c56,Legends - Volume 10,Books,1636,454,17550.54
14,bbc99c6e-1552-4677-8a8f-61a2e541e6c8,Apple Book4 Ultrabook,Electronics,1432,534,17109.10
15,f81e1fd5-a01b-4fbe-81d6-5dc5ab19b03c,Castrol Prime7 Electronic,Automotive,1378,386,18339.44
16,8b875a73-88df-44ff-966d-5649d7a14d31,Nike Womenswear in Olive,Clothing & Accessories,1295,622,19051.00
17,854f59a0-38d4-4e20-b346-43eca5ccb8cb,Nike Classic Accessorie,Clothing & Accessories,1235,628,17841.75
18,3b27636c-a2bd-4c64-b03c-ac8bf64ce0bc,Pyrex Smart Appliance,Home & Kitchen,1158,562,19183.47
19,b47d09df-cbf3-4a7e-a7dc-3d8fba9ede4c,LEGO Prime Deluxe Ella,Toys & Games,948,325,17294.45