In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns

In [2]:
df=pd.read_csv('/content/olist_customers_dataset.csv')

In [3]:
df.duplicated().sum()

np.int64(0)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [5]:
df.describe()

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

In [6]:
df.sample(10)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
44450,067f45ab00b8417ea9d95d1f42f6a41c,26b0aa1978f09039fab41c4e4ed32299,57072,maceio,AL
4978,9ea52a177d36577d2396cad28e68a4e0,db5076501cb0022f454d85f4096c6584,88352,brusque,SC
63538,9eed0427964fdb6119f95015282a94b2,b8d31a82b1bb71983bbc08e4751baeab,4524,sao paulo,SP
94350,3ad431a9d09bcd4b300f4ec8c8c371e6,e6159048f5a21d16728f520efe27c446,12086,taubate,SP
69805,16c38e4b6dac7b5e16a19abe1e10a009,0b6fd6a869a0b5cba9a4b8092ebdf78d,54210,jaboatao dos guararapes,PE
31067,a7056034bcc7c12cd4140957ee3c342a,45aa80c26dcdf6abfdc0b74582ead3f9,11730,mongagua,SP
17747,e39a1b2ef7580c7d050e6e2d941b1ceb,444849193b432d1a714c0cbfe34a1845,25901,mage,RJ
47175,6e8a30827c4d5bd095c436b486502fcc,0b1863ef940d2c99493c2c551d7e3470,76410,campinorte,GO
2691,cf96b5af1c0b18a84eb35a144c85f142,e7c0adb16c7fea6d7f75c3d9e72f813b,2035,sao paulo,SP
93868,aa680976703cc404563da71518e6b940,c1a407e61dad78110e4e5150afe80f8c,8340,sao paulo,SP

In [15]:
df['customer_unique_id'].duplicated().sum()

np.int64(3345)

In [8]:
df['customer_state'].value_counts()

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
PE     1652
CE     1336
PA      975
MT      907
MA      747
MS      715
PB      536
PI      495
RN      485
AL      413
SE      350
TO      280
RO      253
AM      148
AC       81
AP       68
RR       46
Name: count, dtype: int64

In [9]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [14]:
df['customer_city'].value_counts().sample(20)

customer_city
divinolandia                7
carius                      3
salinas da margarida        1
sarzedo                    18
pimenteiras                 2
parnamirim                 63
carmo da mata               6
guabiruba                   5
campo alegre de goias       2
marechal candido rondon    31
tabuleiro                   2
telemaco borba             35
ouro preto                 57
altinho                     2
teixeira de freitas        29
reginopolis                 3
recreio                     3
socorro                    19
alto alegre do pindare      1
gaurama                     3
Name: count, dtype: int64

##All state and Cities are different and their is no grammatically error

In [16]:
from google.colab import files
df.to_csv('Customer_cleaned_data.csv', index=False)
files.download('Customer_cleaned_data.csv')