In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [2]:
df=pd.read_csv('/content/olist_sellers_dataset.csv')

In [3]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [4]:
df.sample(5)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
65,b7e1750c1157341d2abd0251e07c186b,5741,sao paulo,SP
1205,19d62d484cba71963c93f0f00ab42013,89114,gaspar,SC
883,8f2b51a30523cdecddc2f179f351c7d6,4833,sao paulo,SP
1767,0ddefe3c7a032b91f4e25b9c3a08fca1,9721,sao bernardo do campo,SP
242,7d13fca15225358621be4086e1eb0964,14050,ribeirao preto,SP

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [7]:
df.duplicated().sum()

np.int64(0)

In [9]:
df['seller_id'].nunique()

3095

In [12]:
df['seller_city'].nunique()

611

In [16]:
df['seller_city']=df['seller_city'].str.strip().str.lower()

In [17]:
df['seller_city'].nunique()

611

In [18]:
df['seller_city'].value_counts()

seller_city
sao paulo                                   694
curitiba                                    127
rio de janeiro                               96
belo horizonte                               68
ribeirao preto                               52
guarulhos                                    50
ibitinga                                     49
santo andre                                  45
campinas                                     41
maringa                                      40
sao jose do rio preto                        33
sorocaba                                     32
sao bernardo do campo                        32
osasco                                       32
porto alegre                                 28
brasilia                                     28
londrina                                     26
goiania                                      23
joinville                                    22
blumenau                                     21
franca                                       20
sao caetano do sul                           20
florianopolis                                18
sao jose dos campos                          18
caxias do sul                                18
limeira                                      17
santos                                       16
mogi das cruzes                              15
marilia                                      15
bauru                                        14
cascavel                                     14
jundiai                                      14
barueri                                      13
maua                                         13
sao carlos                                   13
piracicaba                                   12
uberlandia                                   12
contagem                                     12
rio claro                                    12
presidente prudente                          12
atibaia                                      11
araraquara                                   11
sao jose dos pinhais                         10
taboao da serra                              10
carapicuiba                                  10
cotia                                        10
juiz de fora                                 10
catanduva                                    10
brusque                                      10
praia grande                                 10
americana                                    10
arapongas                                    10
birigui                                      10
itajai                                       10
canoas                                        9
pedreira                                      9
santana de parnaiba                           9
salto                                         9
itaquaquecetuba                               9
diadema                                       9
porto ferreira                                9
jaragua do sul                                9
apucarana                                     8
mogi guacu                                    8
colombo                                       8
toledo                                        8
assis                                         8
divinopolis                                   8
niteroi                                       8
pinhais                                       8
palhoca                                       8
indaiatuba                                    8
jacarei                                       7
valinhos                                      7
sao roque                                     7
fortaleza                                     7
salvador                                      7
sao goncalo                                   7
novo hamburgo                                 6
ponta grossa                                  6
taubate                                       6
santa rita do sapucai                         6
uba                                           6
fazenda rio grande                            6
ribeirao pires                                6
guaruja                                       6
petropolis                                    6
lencois paulista                              6
claudio                                       6
sao jose                                      5
nova friburgo                                 5
penapolis                                     5
nova iguacu                                   5
betim                                         5
vila velha                                    5
pocos de caldas                               5
sumare                                        5
lajeado                                       5
braganca paulista                             5
recife                                        5
foz do iguacu                                 5
tubarao                                       5
amparo                                        5
mirassol                                      4
itapecerica da serra                          4
itu                                           4
francisco beltrao                             4
aracatuba                                     4
sp                                            4
umuarama                                      4
votorantim                                    4
jaguariuna                                    4
cachoeiro de itapemirim                       4
vitoria                                       4
sete lagoas                                   4
botucatu                                      4
garca                                         4
borda da mata                                 4
formiga                                       4
varginha                                      4
campo grande                                  4
tupa                                          4
rio do sul                                    4
criciuma                                      4
fernandopolis                                 4
santa barbara d'oeste                         4
barra mansa                                   4
jau                                           4
barretos                                      4
capivari                                      4
paulinia                                      4
itatiba                                       4
jaci                                          4
itapevi                                       4
votuporanga                                   4
araguari                                      4
tabatinga                                     3
tatui                                         3
laranjal paulista                             3
anapolis                                      3
carazinho                                     3
cachoeirinha                                  3
uberaba                                       3
santa maria                                   3
navegantes                                    3
pelotas                                       3
santa terezinha de itaipu                     3
sao bento do sul                              3
duque de caxias                               3
mesquita                                      3
balneario camboriu                            3
pompeia                                       3
marechal candido rondon                       3
sarandi                                       3
suzano                                        3
morrinhos                                     3
cambe                                         3
loanda                                        3
sao joao de meriti                            3
campo largo                                   3
chapeco                                       3
vargem grande do sul                          3
jacutinga                                     3
conselheiro lafaiete                          3
aruja                                         3
montes claros                                 3
boituva                                       3
bento goncalves                               3
batatais                                      3
artur nogueira                                3
rolandia                                      3
ferraz de vasconcelos                         3
osvaldo cruz                                  3
araras                                        3
venancio aires                                3
sao paulo - sp                                3
mogi mirim                                    3
guaratuba                                     3
tres coracoes                                 3
macae                                         3
serra                                         3
serra negra                                   3
xanxere                                       2
ribeirao das neves                            2
sao leopoldo                                  2
sao pedro                                     2
pitanga                                       2
timbo                                         2
santa rosa                                    2
alfenas                                       2
franco da rocha                               2
treze tilias                                  2
paulo lopes                                   2
castro                                        2
farroupilha                                   2
tanabi                                        2
natal                                         2
andradas                                      2
nova odessa                                   2
nilopolis                                     2
viamao                                        2
lauro de freitas                              2
imbituba                                      2
canoinhas                                     2
araxa                                         2
tiradentes                                    2
baependi                                      2
bariri                                        2
lorena                                        2
rodeio                                        2
belford roxo                                  2
cariacica                                     2
lagoa da prata                                2
uruacu                                        2
teresopolis                                   2
videira                                       2
porto belo                                    2
embu das artes                                2
registro                                      2
cafelandia                                    2
estancia velha                                2
conchal                                       2
campo bom                                     2
rio bonito                                    2
gaspar                                        2
itapetininga                                  2
pinhalzinho                                   2
guaira                                        2
joao pessoa                                   2
bady bassitt                                  2
araucaria                                     2
cosmopolis                                    2
volta redonda                                 2
santa barbara d´oeste                         2
itaipulandia                                  2
patos de minas                                2
ipira                                         2
caruaru                                       2
cuiaba                                        2
jaboticabal                                   2
indaial                                       2
laurentino                                    2
itajobi                                       2
jaguaruna                                     2
mairipora                                     2
montenegro                                    2
flores da cunha                               2
dois corregos                                 2
formosa                                       2
armacao dos buzios                            2
coronel fabriciano                            2
campo limpo paulista                          2
cajamar                                       2
sao joao del rei                              2
echapora                                      2
pradopolis                                    2
pato branco                                   2
igaracu do tiete                              2
vicosa                                        2
dores de campos                               2
sao jose do rio pardo                         2
ipatinga                                      2
hortolandia                                   2
curitibanos                                   2
itauna                                        2
lages                                         2
garopaba                                      2
sao ludgero                                   2
sombrio                                       2
leme                                          1
brejao                                        1
itirapina                                     1
porto seguro                                  1
marica                                        1
jaragua                                       1
uniao da vitoria                              1
jussara                                       1
barrinha                                      1
itabira                                       1
ilicinea                                      1
campo mourao                                  1
pinhalao                                      1
presidente bernardes                          1
cananeia                                      1
queimados                                     1
gama                                          1
cacador                                       1
robeirao preto                                1
ourinhos                                      1
dracena                                       1
sao sebastiao da grama/sp                     1
bom jardim                                    1
paracambi                                     1
porto velho                                   1
divisa nova                                   1
laguna                                        1
mogi das cruses                               1
brasilia df                                   1
ampere                                        1
arinos                                        1
pato bragado                                  1
ararangua                                     1
holambra                                      1
pedrinhas paulista                            1
sabara                                        1
oliveira                                      1
itau de minas                                 1
messias targino                               1
ipe                                           1
santo andre/sao paulo                         1
muriae                                        1
cruzeiro                                      1
entre rios do oeste                           1
ubatuba                                       1
pacatuba                                      1
arraial d'ajuda (porto seguro)                1
sbc/sp                                        1
presidente epitacio                           1
pitangueiras                                  1
teresina                                      1
imbituva                                      1
sao francisco do sul                          1
serra redonda                                 1
juzeiro do norte                              1
mucambo                                       1
prados                                        1
cariacica / es                                1
pilar do sul                                  1
novo horizonte                                1
fronteira                                     1
aperibe                                       1
parai                                         1
guaimbe                                       1
angra dos reis                                1
sp / sp                                       1
pirassununga                                  1
taruma                                        1
s jose do rio preto                           1
domingos martins                              1
mombuca                                       1
poa                                           1
sao  jose dos pinhais                         1
congonhas                                     1
serrana                                       1
floranopolis                                  1
novo hamburgo, rio grande do sul, brasil      1
araquari                                      1
bonfinopolis de minas                         1
guarapuava                                    1
sinop                                         1
joao pinheiro                                 1
santa catarina                                1
aracaju                                       1
torres                                        1
pedregulho                                    1
mococa                                        1
paraiba do sul                                1
viana                                         1
brotas                                        1
bom jesus dos perdoes                         1
maua/sao paulo                                1
itaporanga                                    1
rolante                                       1
monte alegre do sul                           1
lagoa santa                                   1
garuva                                        1
monte siao                                    1
04482255                                      1
santa barbara d oeste                         1
cordeiropolis                                 1
campo do meio                                 1
mogi das cruzes / sp                          1
lambari                                       1
colatina                                      1
guara                                         1
sao bernardo do capo                          1
marialva                                      1
vargem grande paulista                        1
mandaguari                                    1
sao miguel do oeste                           1
coxim                                         1
irece                                         1
monte alto                                    1
horizontina                                   1
icara                                         1
tocantins                                     1
passos                                        1
vespasiano                                    1
mandirituba                                   1
monteiro lobato                               1
cascavael                                     1
bahia                                         1
rio branco                                    1
jales                                         1
luiz alves                                    1
são paulo                                    1
barro alto                                    1
joao monlevade                                1
luziania                                      1
floresta                                      1
braco do norte                                1
santa cecilia                                 1
rio de janeiro \rio de janeiro                1
sao pauo                                      1
vicente de carvalho                           1
sertanopolis                                  1
igrejinha                                     1
janauba                                       1
tiete                                         1
sao jose dos pinhas                           1
ouro fino                                     1
campos dos goytacazes                         1
sao bento                                     1
concordia                                     1
piracanjuba                                   1
campanha                                      1

In [20]:
print(df['seller_city'].value_counts().index.tolist())

['sao paulo', 'curitiba', 'rio de janeiro', 'belo horizonte', 'ribeirao preto', 'guarulhos', 'ibitinga', 'santo andre', 'campinas', 'maringa', 'sao jose do rio preto', 'sorocaba', 'sao bernardo do campo', 'osasco', 'porto alegre', 'brasilia', 'londrina', 'goiania', 'joinville', 'blumenau', 'franca', 'sao caetano do sul', 'florianopolis', 'sao jose dos campos', 'caxias do sul', 'limeira', 'santos', 'mogi das cruzes', 'marilia', 'bauru', 'cascavel', 'jundiai', 'barueri', 'maua', 'sao carlos', 'piracicaba', 'uberlandia', 'contagem', 'rio claro', 'presidente prudente', 'atibaia', 'araraquara', 'sao jose dos pinhais', 'taboao da serra', 'carapicuiba', 'cotia', 'juiz de fora', 'catanduva', 'brusque', 'praia grande', 'americana', 'arapongas', 'birigui', 'itajai', 'canoas', 'pedreira', 'santana de parnaiba', 'salto', 'itaquaquecetuba', 'diadema', 'porto ferreira', 'jaragua do sul', 'apucarana', 'mogi guacu', 'colombo', 'toledo', 'assis', 'divinopolis', 'niteroi', 'pinhais', 'palhoca', 'indaiatuba', 'jacarei', 'valinhos', 'sao roque', 'fortaleza', 'salvador', 'sao goncalo', 'novo hamburgo', 'ponta grossa', 'taubate', 'santa rita do sapucai', 'uba', 'fazenda rio grande', 'ribeirao pires', 'guaruja', 'petropolis', 'lencois paulista', 'claudio', 'sao jose', 'nova friburgo', 'penapolis', 'nova iguacu', 'betim', 'vila velha', 'pocos de caldas', 'sumare', 'lajeado', 'braganca paulista', 'recife', 'foz do iguacu', 'tubarao', 'amparo', 'mirassol', 'itapecerica da serra', 'itu', 'francisco beltrao', 'aracatuba', 'sp', 'umuarama', 'votorantim', 'jaguariuna', 'cachoeiro de itapemirim', 'vitoria', 'sete lagoas', 'botucatu', 'garca', 'borda da mata', 'formiga', 'varginha', 'campo grande', 'tupa', 'rio do sul', 'criciuma', 'fernandopolis', "santa barbara d'oeste", 'barra mansa', 'jau', 'barretos', 'capivari', 'paulinia', 'itatiba', 'jaci', 'itapevi', 'votuporanga', 'araguari', 'tabatinga', 'tatui', 'laranjal paulista', 'anapolis', 'carazinho', 'cachoeirinha', 'uberaba', 'santa maria', 'navegantes', 'pelotas', 'santa terezinha de itaipu', 'sao bento do sul', 'duque de caxias', 'mesquita', 'balneario camboriu', 'pompeia', 'marechal candido rondon', 'sarandi', 'suzano', 'morrinhos', 'cambe', 'loanda', 'sao joao de meriti', 'campo largo', 'chapeco', 'vargem grande do sul', 'jacutinga', 'conselheiro lafaiete', 'aruja', 'montes claros', 'boituva', 'bento goncalves', 'batatais', 'artur nogueira', 'rolandia', 'ferraz de vasconcelos', 'osvaldo cruz', 'araras', 'venancio aires', 'sao paulo - sp', 'mogi mirim', 'guaratuba', 'tres coracoes', 'macae', 'serra', 'serra negra', 'xanxere', 'ribeirao das neves', 'sao leopoldo', 'sao pedro', 'pitanga', 'timbo', 'santa rosa', 'alfenas', 'franco da rocha', 'treze tilias', 'paulo lopes', 'castro', 'farroupilha', 'tanabi', 'natal', 'andradas', 'nova odessa', 'nilopolis', 'viamao', 'lauro de freitas', 'imbituba', 'canoinhas', 'araxa', 'tiradentes', 'baependi', 'bariri', 'lorena', 'rodeio', 'belford roxo', 'cariacica', 'lagoa da prata', 'uruacu', 'teresopolis', 'videira', 'porto belo', 'embu das artes', 'registro', 'cafelandia', 'estancia velha', 'conchal', 'campo bom', 'rio bonito', 'gaspar', 'itapetininga', 'pinhalzinho', 'guaira', 'joao pessoa', 'bady bassitt', 'araucaria', 'cosmopolis', 'volta redonda', 'santa barbara d´oeste', 'itaipulandia', 'patos de minas', 'ipira', 'caruaru', 'cuiaba', 'jaboticabal', 'indaial', 'laurentino', 'itajobi', 'jaguaruna', 'mairipora', 'montenegro', 'flores da cunha', 'dois corregos', 'formosa', 'armacao dos buzios', 'coronel fabriciano', 'campo limpo paulista', 'cajamar', 'sao joao del rei', 'echapora', 'pradopolis', 'pato branco', 'igaracu do tiete', 'vicosa', 'dores de campos', 'sao jose do rio pardo', 'ipatinga', 'hortolandia', 'curitibanos', 'itauna', 'lages', 'garopaba', 'sao ludgero', 'sombrio', 'leme', 'brejao', 'itirapina', 'porto seguro', 'marica', 'jaragua', 'uniao da vitoria', 'jussara', 'barrinha', 'itabira', 'ilicinea', 'campo mourao', 'pinhalao', 'presidente bernardes', 'cananeia', 'queimados', 'gama', 'cacador', 'robeirao preto', 'ourinhos', 'dracena', 'sao sebastiao da grama/sp', 'bom jardim', 'paracambi', 'porto velho', 'divisa nova', 'laguna', 'mogi das cruses', 'brasilia df', 'ampere', 'arinos', 'pato bragado', 'ararangua', 'holambra', 'pedrinhas paulista', 'sabara', 'oliveira', 'itau de minas', 'messias targino', 'ipe', 'santo andre/sao paulo', 'muriae', 'cruzeiro', 'entre rios do oeste', 'ubatuba', 'pacatuba', "arraial d'ajuda (porto seguro)", 'sbc/sp', 'presidente epitacio', 'pitangueiras', 'teresina', 'imbituva', 'sao francisco do sul', 'serra redonda', 'juzeiro do norte', 'mucambo', 'prados', 'cariacica / es', 'pilar do sul', 'novo horizonte', 'fronteira', 'aperibe', 'parai', 'guaimbe', 'angra dos reis', 'sp / sp', 'pirassununga', 'taruma', 's jose do rio preto', 'domingos martins', 'mombuca', 'poa', 'sao  jose dos pinhais', 'congonhas', 'serrana', 'floranopolis', 'novo hamburgo, rio grande do sul, brasil', 'araquari', 'bonfinopolis de minas', 'guarapuava', 'sinop', 'joao pinheiro', 'santa catarina', 'aracaju', 'torres', 'pedregulho', 'mococa', 'paraiba do sul', 'viana', 'brotas', 'bom jesus dos perdoes', 'maua/sao paulo', 'itaporanga', 'rolante', 'monte alegre do sul', 'lagoa santa', 'garuva', 'monte siao', '04482255', 'santa barbara d oeste', 'cordeiropolis', 'campo do meio', 'mogi das cruzes / sp', 'lambari', 'colatina', 'guara', 'sao bernardo do capo', 'marialva', 'vargem grande paulista', 'mandaguari', 'sao miguel do oeste', 'coxim', 'irece', 'monte alto', 'horizontina', 'icara', 'tocantins', 'passos', 'vespasiano', 'mandirituba', 'monteiro lobato', 'cascavael', 'bahia', 'rio branco', 'jales', 'luiz alves', 'são paulo', 'barro alto', 'joao monlevade', 'luziania', 'floresta', 'braco do norte', 'santa cecilia', 'rio de janeiro \\rio de janeiro', 'sao pauo', 'vicente de carvalho', 'sertanopolis', 'igrejinha', 'janauba', 'tiete', 'sao jose dos pinhas', 'ouro fino', 'campos dos goytacazes', 'sao bento', 'concordia', 'piracanjuba', 'campanha', 'uruguaiana', 'santo antonio de posse', 'sao joaquim da barra', 'marapoama', 'cerqueira cesar', 'andira-pr', 'ivoti', 'belo horizont', 'bertioga', 'almirante tamandare', 'bebedouro', 'cravinhos', 'portoferreira', 'tres rios', 'paincandu', 'santo angelo', 'parnamirim', 'vera cruz', 'barbacena/ minas gerais', 'tres coroas', 'sao paulo / sao paulo', 'auriflama/sp', 'caratinga', 'resende', 'campina grande', 'pederneiras', 'goioere', 'angra dos reis rj', 'olimpia', 'extrema', 'sando andre', 'rio de janeiro / rio de janeiro', 'sao paulo sp', 'mairinque', 'imigrante', 'mineiros do tiete', 'neopolis', 'sbc', 'itapui', 'miguelopolis', 'sao pedro da aldeia', 'campina das missoes', 'castro pires', 'fernando prestes', 'carmo do cajuru', 'ao bernardo do campo', 'portao', 'pinhais/pr', 'sao vicente', 'sao  paulo', 'ronda alta', 'ponte nova', 'mamanguape', 'laranjeiras do sul', 'mirandopolis', 'ferraz de  vasconcelos', 'balenario camboriu', 'jaciara', 'taio', 'bage', 'descalvado', 'erechim', 'buritama', 'caieiras', 'barbacena', 'nova lima', 'varzea paulista', 'abadia de goias', 'cataguases', 'aparecida', 'paraiso do sul', 'embu guacu', 'sao paluo', 'campo magro', 'eusebio', 'sao jose do rio pret', 'sao luis', 'nova trento', 'camboriu', 'ribeirao preto / sao paulo', 'nova petropolis', 'jarinu', 'garulhos', 'engenheiro coelho', 'eunapolis', 'guiricema', 'arvorezinha', 'santa terezinha de goias', 'formosa do oeste', 'orleans', 'nhandeara', 'campos novos', 'presidente getulio', 'santo antonio de padua', 'guanhaes', 'louveira', 'vassouras', 'ji parana', 'alambari', 'rio do oeste', 'itaborai', 'lages - sc', 'mandaguacu', 'teixeira soares', 'sao joao da boa vista', 'macatuba', 'sao sebastiao', 'itapeva', 'orlandia', 'bombinhas', 'parana', 'centro', 'carapicuiba / sao paulo', 'afonso claudio', 'rio das pedras', 'minas gerais', 'terra boa', 'manaus', 'xaxim', 'rio grande', 'francisco morato', 'clementina', 'rio negrinho', 'soledade', 'imbe', 'ilheus', 'bocaiuva do sul', 'socorro', 'sao paulop', 'mateus leme', 'vendas@creditparts.com.br', 'pedro leopoldo', 'santo antonio da patrulha', 'barra velha', 'saquarema', 'congonhal', 'ouro preto', 'carmo da mata', 'cordilheira alta', 'caucaia', 'guanambi', 'ibia', 'condor', 'auriflama', 'santa maria da serra', 'ibirite', 'avare', 'guariba', 'cachoeira do sul', 'camanducaia', 'tres de maio', 'feira de santana', 'cianorte', 'ribeirao pretp', 'aguas claras df', 'jambeiro', 'pirituba', 'cornelio procopio', 'massaranduba', 'medianeira', 'scao jose do rio pardo', 'alvares machado', 'santa rosa de viterbo', 'governador valadares', 'palotina', 'vitoria de santo antao', 'picarras', 'bofete', 'tabao da serra', 'mage', 'rio verde', 'ipaussu', 'alvorada', 'paranavai', 'sapiranga', 'itapema', 'colorado', 'santa cruz do sul', 'triunfo', 'japira', 'california', "sao miguel d'oeste", 'bandeirantes', 'aparecida de goiania', 'riberao preto', 'irati', 'tambau', 'guaratingueta', 'varzea alegre', 'jacarei / sao paulo', 'ipua', 'muqui', 'timoteo', 'pouso alegre', 'rio de janeiro, rio de janeiro, brasil']

In [21]:
df[df['seller_city']=='sao paulo - sp']

,seller_id,seller_zip_code_prefix,seller_city,seller_state
826,05e107217c7266362fd44b75b2cd4cc4,5353,sao paulo - sp,SP
1580,8090490573c6c0aa343a7231ebcb8c86,4130,sao paulo - sp,SP
2946,06579cb253ecd5a3a12a9e6eb6bf8f47,4007,sao paulo - sp,SP

In [22]:
city_corrections = {
    'sao pauo': 'sao paulo',
    'sao paluo': 'sao paulo',
    'sao paulop': 'sao paulo',
    'sao  paulo': 'sao paulo',
    'sao paulo - sp': 'sao paulo',
    'sao paulo sp': 'sao paulo',
    'sao paulo / sao paulo': 'sao paulo',
    'são paulo': 'sao paulo',

    'ribeirao pretp': 'ribeirao preto',
    'robeirao preto': 'ribeirao preto',
    'riberao preto': 'ribeirao preto',

    'mogi das cruses': 'mogi das cruzes',
    'floranopolis': 'florianopolis',
    'cascavael': 'cascavel',
    'sando andre': 'santo andre',
    'garulhos': 'guarulhos',
    'belo horizont': 'belo horizonte',

    'sao bernardo do capo': 'sao bernardo do campo',
    'sao jose dos pinhas': 'sao jose dos pinhais',
    'balenario camboriu': 'balneario camboriu',

    'sao jose do rio pret': 'sao jose do rio preto',
    'scao jose do rio pardo': 'sao jose do rio pardo',

    'tabao da serra': 'taboao da serra',
    'paincandu': 'paicandu',
    'juzeiro do norte': 'juazeiro do norte',

    'ferraz de  vasconcelos': 'ferraz de vasconcelos'
}

In [23]:
df['seller_city']=df['seller_city'].replace(city_corrections)

In [24]:
city_corrections.update({
    'mogi das cruzes / sp': 'mogi das cruzes',
    'sbc/sp': 'sao bernardo do campo',
    'sbc': 'sao bernardo do campo',
    'pinhais/pr': 'pinhais',
    'maua/sao paulo': 'maua',
    'santo andre/sao paulo': 'santo andre',
    'carapicuiba / sao paulo': 'carapicuiba',
    'ribeirao preto / sao paulo': 'ribeirao preto',
    'cariacica / es': 'cariacica',
    'pinhais/pr': 'pinhais',
    'auriflama/sp': 'auriflama',
    'lages - sc': 'lages',
    'brasilia df': 'brasilia',
    'novo hamburgo, rio grande do sul, brasil': 'novo hamburgo',
    'rio de janeiro, rio de janeiro, brasil': 'rio de janeiro',
    'rio de janeiro / rio de janeiro': 'rio de janeiro',
})

In [25]:
df['seller_city']=df['seller_city'].replace(city_corrections)

In [26]:
invalid = [
    '04482255',
    'vendas@creditparts.com.br'
]
df.loc[df['seller_city'].isin(invalid),'seller_city']=None

In [29]:
df['seller_city'].nunique()

570

In [30]:
print(df['seller_city'].value_counts().index.tolist())

['sao paulo', 'curitiba', 'rio de janeiro', 'belo horizonte', 'ribeirao preto', 'guarulhos', 'ibitinga', 'santo andre', 'campinas', 'maringa', 'sao bernardo do campo', 'sao jose do rio preto', 'osasco', 'sorocaba', 'brasilia', 'porto alegre', 'londrina', 'goiania', 'joinville', 'blumenau', 'sao caetano do sul', 'franca', 'florianopolis', 'caxias do sul', 'sao jose dos campos', 'mogi das cruzes', 'limeira', 'santos', 'marilia', 'cascavel', 'jundiai', 'bauru', 'maua', 'barueri', 'sao carlos', 'rio claro', 'piracicaba', 'uberlandia', 'presidente prudente', 'contagem', 'araraquara', 'sao jose dos pinhais', 'taboao da serra', 'atibaia', 'carapicuiba', 'arapongas', 'brusque', 'birigui', 'juiz de fora', 'praia grande', 'catanduva', 'itajai', 'americana', 'cotia', 'porto ferreira', 'salto', 'canoas', 'pedreira', 'diadema', 'jaragua do sul', 'pinhais', 'itaquaquecetuba', 'santana de parnaiba', 'indaiatuba', 'divinopolis', 'toledo', 'colombo', 'apucarana', 'niteroi', 'assis', 'mogi guacu', 'palhoca', 'sao goncalo', 'sao roque', 'fortaleza', 'jacarei', 'salvador', 'novo hamburgo', 'valinhos', 'claudio', 'taubate', 'uba', 'petropolis', 'lencois paulista', 'ponta grossa', 'fazenda rio grande', 'guaruja', 'ribeirao pires', 'santa rita do sapucai', 'amparo', 'braganca paulista', 'penapolis', 'sao jose', 'tubarao', 'recife', 'sumare', 'foz do iguacu', 'betim', 'vila velha', 'lajeado', 'nova iguacu', 'nova friburgo', 'pocos de caldas', 'cachoeiro de itapemirim', 'aracatuba', 'sete lagoas', "santa barbara d'oeste", 'tupa', 'paulinia', 'itatiba', 'jaci', 'capivari', 'fernandopolis', 'campo grande', 'barretos', 'jau', 'sp', 'umuarama', 'vitoria', 'criciuma', 'votorantim', 'botucatu', 'garca', 'barra mansa', 'varginha', 'formiga', 'francisco beltrao', 'votuporanga', 'araguari', 'rio do sul', 'itapecerica da serra', 'itapevi', 'ferraz de vasconcelos', 'jaguariuna', 'borda da mata', 'itu', 'balneario camboriu', 'mirassol', 'duque de caxias', 'anapolis', 'sao bento do sul', 'mogi mirim', 'loanda', 'santa terezinha de itaipu', 'araras', 'campo largo', 'carazinho', 'lages', 'sao joao de meriti', 'cariacica', 'tabatinga', 'montes claros', 'boituva', 'rolandia', 'sao jose do rio pardo', 'macae', 'jacutinga', 'cambe', 'artur nogueira', 'serra negra', 'guaratuba', 'pelotas', 'conselheiro lafaiete', 'bento goncalves', 'tatui', 'tres coracoes', 'suzano', 'santa maria', 'batatais', 'navegantes', 'venancio aires', 'marechal candido rondon', 'vargem grande do sul', 'chapeco', 'morrinhos', 'sarandi', 'uberaba', 'pompeia', 'mesquita', 'cachoeirinha', 'laranjal paulista', 'serra', 'aruja', 'osvaldo cruz', 'itaipulandia', 'echapora', 'conchal', 'araucaria', 'itajobi', 'indaial', 'laurentino', 'alfenas', 'rodeio', 'vicosa', 'pradopolis', 'sao joao del rei', 'bady bassitt', 'lorena', 'pato branco', 'coronel fabriciano', 'sao ludgero', 'igaracu do tiete', 'dores de campos', 'teresopolis', 'ipatinga', 'hortolandia', 'curitibanos', 'lagoa da prata', 'campo limpo paulista', 'garopaba', 'xanxere', 'armacao dos buzios', 'flores da cunha', 'sao pedro', 'bariri', 'formosa', 'belford roxo', 'cajamar', 'baependi', 'tiradentes', 'jaboticabal', 'ipira', 'gaspar', 'rio bonito', 'itauna', 'pinhalzinho', 'itapetininga', 'santa barbara d´oeste', 'viamao', 'caruaru', 'sombrio', 'campo bom', 'uruacu', 'porto belo', 'araxa', 'canoinhas', 'imbituba', 'pitanga', 'tanabi', 'videira', 'nilopolis', 'lauro de freitas', 'natal', 'santa rosa', 'embu das artes', 'registro', 'estancia velha', 'andradas', 'nova odessa', 'auriflama', 'cafelandia', 'timbo', 'dois corregos', 'montenegro', 'joao pessoa', 'patos de minas', 'cosmopolis', 'ribeirao das neves', 'jaguaruna', 'castro', 'sao leopoldo', 'guaira', 'franco da rocha', 'mairipora', 'paulo lopes', 'volta redonda', 'cuiaba', 'treze tilias', 'farroupilha', 'carmo do cajuru', 'fernando prestes', 'ji parana', 'nova petropolis', 'vassouras', 'alambari', 'ao bernardo do campo', 'camboriu', 'portao', 'sao luis', 'nova trento', 'louveira', 'sao vicente', 'guanhaes', 'santo antonio de padua', 'presidente getulio', 'angra dos reis rj', 'castro pires', 'descalvado', 'campo magro', 'bage', 'embu guacu', 'erechim', 'paraiso do sul', 'buritama', 'taio', 'eusebio', 'caieiras', 'aparecida', 'miguelopolis', 'barbacena', 'nova lima', 'varzea paulista', 'cataguases', 'mineiros do tiete', 'neopolis', 'itapui', 'jarinu', 'sao pedro da aldeia', 'abadia de goias', 'campina das missoes', 'brejao', 'itapema', 'colorado', 'santa cruz do sul', 'triunfo', 'uniao da vitoria', 'jussara', 'itabira', 'ilicinea', 'campo mourao', 'pinhalao', 'presidente bernardes', 'ronda alta', 'queimados', 'gama', 'cacador', 'ourinhos', 'dracena', 'sao sebastiao da grama/sp', 'guariba', 'cachoeira do sul', 'feira de santana', 'cianorte', 'aguas claras df', 'cananeia', 'palotina', 'vitoria de santo antao', 'bandeirantes', 'aparecida de goiania', 'irati', 'tambau', 'guaratingueta', 'varzea alegre', 'jacarei / sao paulo', 'ipua', 'muqui', 'sapiranga', 'pouso alegre', 'governador valadares', 'barrinha', 'leme', 'picarras', 'bofete', 'mage', 'rio verde', 'ipaussu', 'alvorada', 'paranavai', 'timoteo', 'rio negrinho', 'soledade', 'imbe', 'ilheus', 'bocaiuva do sul', 'socorro', 'mateus leme', 'rio do oeste', 'mandaguacu', 'teixeira soares', 'sao joao da boa vista', 'jambeiro', 'sao sebastiao', 'itapeva', 'orlandia', 'bombinhas', 'parana', 'centro', 'afonso claudio', 'rio das pedras', 'engenheiro coelho', 'eunapolis', 'campos novos', 'macatuba', 'pirituba', 'cornelio procopio', 'massaranduba', 'medianeira', 'alvares machado', 'santa rosa de viterbo', 'pedro leopoldo', 'ouro preto', 'carmo da mata', 'cordilheira alta', 'caucaia', 'clementina', 'ibia', 'condor', 'santa maria da serra', 'ibirite', 'avare', 'minas gerais', 'terra boa', 'manaus', 'xaxim', 'rio grande', 'francisco morato', 'guanambi', 'pilar do sul', 'novo horizonte', 'fronteira', 'itaborai', 'aperibe', 'parai', 'guaimbe', 'sao  jose dos pinhais', 'congonhas', 'marialva', 'araquari', 'nhandeara', 'bonfinopolis de minas', 'garuva', 'monte siao', 'orleans', 'santa barbara d oeste', 'cordeiropolis', 'campo do meio', 'serrana', 'arinos', 'pato bragado', 'ararangua', 'holambra', 'pedrinhas paulista', 'sabara', 'oliveira', 'itau de minas', 'japira', 'prados', "sao miguel d'oeste", 'teresina', 'imbituva', 'sao francisco do sul', 'serra redonda', 'bom jardim', 'paracambi', 'porto velho', 'mucambo', 'california', 'barro alto', 'mamanguape', 'ponte nova', 'concordia', 'piracanjuba', 'campanha', 'uruguaiana', 'santo antonio de posse', 'sao joaquim da barra', 'formosa do oeste', 'mandirituba', 'goioere', 'pederneiras', 'campina grande', 'resende', 'vicente de carvalho', 'caratinga', 'sertanopolis', 'tres coroas', 'vespasiano', 'mombuca', 'santa terezinha de goias', 'arvorezinha', 'poa', 'guiricema', 'monte alto', 'horizontina', 'icara', 'tocantins', 'luiz alves', 'jaciara', 'mococa', 'paraiba do sul', 'viana', 'monteiro lobato', 'bahia', 'rio branco', 'mirandopolis', 'jales', 'laranjeiras do sul', 'passos', 'porto seguro', 'janauba', 'tiete', 'ouro fino', 'campos dos goytacazes', 'sao bento', 'joao monlevade', 'luziania', 'floresta', 'ampere', 'santa cecilia', 'rio de janeiro \\rio de janeiro', 'lambari', 'colatina', 'guara', 'vargem grande paulista', 'mandaguari', 'sao miguel do oeste', 'tres de maio', 'braco do norte', 'olimpia', 'extrema', 'jaragua', 'mairinque', 'imigrante', 'marapoama', 'cerqueira cesar', 'andira-pr', 'ivoti', 'igrejinha', 'almirante tamandare', 'bebedouro', 'cravinhos', 'portoferreira', 'tres rios', 'paicandu', 'santo angelo', 'parnamirim', 'vera cruz', 'barbacena/ minas gerais', 'bertioga', 's jose do rio preto', 'domingos martins', 'congonhal', 'messias targino', 'ipe', 'muriae', 'cruzeiro', 'saquarema', 'entre rios do oeste', 'coxim', 'marica', 'pacatuba', "arraial d'ajuda (porto seguro)", 'presidente epitacio', 'barra velha', 'santo antonio da patrulha', 'pitangueiras', 'divisa nova', 'laguna', 'ubatuba', 'irece', 'brotas', 'bom jesus dos perdoes', 'itaporanga', 'rolante', 'monte alegre do sul', 'camanducaia', 'lagoa santa', 'itirapina', 'taruma', 'sinop', 'joao pinheiro', 'santa catarina', 'aracaju', 'torres', 'pedregulho', 'juazeiro do norte', 'angra dos reis', 'sp / sp', 'pirassununga', 'guarapuava']

In [32]:
city_corrections = {
    'sp': 'sao paulo',
    'ao bernardo do campo': 'sao bernardo do campo',
    'sao  jose dos pinhais': 'sao jose dos pinhais',
    'sao sebastiao da grama/sp': 'sao sebastiao da grama',
    'jacarei / sao paulo': 'jacarei',
    'aguas claras df': 'aguas claras',
    'angra dos reis rj': 'angra dos reis',
    'andira-pr': 'andira',
    'barbacena/ minas gerais': 'barbacena',
    'rio de janeiro \\rio de janeiro': 'rio de janeiro',
    's jose do rio preto': 'sao jose do rio preto',
    'paicandu': 'paicandu',
    'sp / sp': 'sao paulo',

    # Santa Barbara d'Oeste variations
    "santa barbara d'oeste": "santa barbara d'oeste",
    "santa barbara d´oeste": "santa barbara d'oeste",
    "santa barbara d oeste": "santa barbara d'oeste"
}

df['seller_city'] = df['seller_city'].replace(city_corrections)

In [33]:
df['seller_city'].nunique()

559

In [34]:
print(df['seller_city'].value_counts().index.tolist())

['sao paulo', 'curitiba', 'rio de janeiro', 'belo horizonte', 'ribeirao preto', 'guarulhos', 'ibitinga', 'santo andre', 'campinas', 'maringa', 'sao bernardo do campo', 'sao jose do rio preto', 'osasco', 'sorocaba', 'brasilia', 'porto alegre', 'londrina', 'goiania', 'joinville', 'blumenau', 'franca', 'sao caetano do sul', 'florianopolis', 'caxias do sul', 'sao jose dos campos', 'limeira', 'mogi das cruzes', 'santos', 'marilia', 'cascavel', 'bauru', 'jundiai', 'maua', 'sao carlos', 'barueri', 'rio claro', 'contagem', 'presidente prudente', 'uberlandia', 'sao jose dos pinhais', 'piracicaba', 'atibaia', 'taboao da serra', 'araraquara', 'carapicuiba', 'americana', 'juiz de fora', 'arapongas', 'itajai', 'praia grande', 'brusque', 'birigui', 'catanduva', 'cotia', 'jaragua do sul', 'porto ferreira', 'diadema', 'pinhais', 'canoas', 'pedreira', 'salto', 'santana de parnaiba', 'itaquaquecetuba', 'divinopolis', 'apucarana', 'colombo', 'mogi guacu', 'indaiatuba', 'niteroi', 'toledo', 'jacarei', 'assis', 'palhoca', 'sao goncalo', 'fortaleza', 'salvador', 'sao roque', "santa barbara d'oeste", 'novo hamburgo', 'valinhos', 'ribeirao pires', 'ponta grossa', 'uba', 'santa rita do sapucai', 'taubate', 'guaruja', 'petropolis', 'lencois paulista', 'claudio', 'fazenda rio grande', 'nova iguacu', 'braganca paulista', 'vila velha', 'sao jose', 'tubarao', 'sumare', 'pocos de caldas', 'betim', 'nova friburgo', 'amparo', 'lajeado', 'penapolis', 'foz do iguacu', 'recife', 'mirassol', 'paulinia', 'araguari', 'itatiba', 'tupa', 'jau', 'umuarama', 'jaguariuna', 'aracatuba', 'francisco beltrao', 'jaci', 'barretos', 'cachoeiro de itapemirim', 'capivari', 'rio do sul', 'votorantim', 'fernandopolis', 'sete lagoas', 'borda da mata', 'itapecerica da serra', 'ferraz de vasconcelos', 'itu', 'vitoria', 'varginha', 'botucatu', 'balneario camboriu', 'votuporanga', 'itapevi', 'garca', 'criciuma', 'barra mansa', 'campo grande', 'formiga', 'tres coracoes', 'cambe', 'lages', 'bento goncalves', 'pelotas', 'santa terezinha de itaipu', 'serra', 'vargem grande do sul', 'tatui', 'tabatinga', 'morrinhos', 'sarandi', 'sao bento do sul', 'duque de caxias', 'marechal candido rondon', 'mogi mirim', 'carazinho', 'aruja', 'venancio aires', 'navegantes', 'santa maria', 'araras', 'cachoeirinha', 'uberaba', 'jacutinga', 'campo largo', 'macae', 'conselheiro lafaiete', 'sao joao de meriti', 'loanda', 'osvaldo cruz', 'batatais', 'chapeco', 'cariacica', 'rolandia', 'boituva', 'sao jose do rio pardo', 'pompeia', 'laranjal paulista', 'mesquita', 'guaratuba', 'montes claros', 'suzano', 'serra negra', 'artur nogueira', 'anapolis', 'sao leopoldo', 'ribeirao das neves', 'volta redonda', 'campo bom', 'porto belo', 'xanxere', 'cajamar', 'campo limpo paulista', 'armacao dos buzios', 'sao ludgero', 'garopaba', 'indaial', 'rodeio', 'lorena', 'bariri', 'baependi', 'tiradentes', 'ipira', 'itaipulandia', 'patos de minas', 'dois corregos', 'joao pessoa', 'cosmopolis', 'pitanga', 'pinhalzinho', 'itapetininga', 'embu das artes', 'registro', 'nova odessa', 'andradas', 'natal', 'tanabi', 'barbacena', 'canoinhas', 'vicosa', 'itajobi', 'jaguaruna', 'mairipora', 'guaira', 'araxa', 'pradopolis', 'echapora', 'jaboticabal', 'viamao', 'castro', 'farroupilha', 'paulo lopes', 'treze tilias', 'franco da rocha', 'alfenas', 'conchal', 'nilopolis', 'santa rosa', 'sao joao del rei', 'pato branco', 'rio bonito', 'gaspar', 'caruaru', 'cuiaba', 'teresopolis', 'lagoa da prata', 'belford roxo', 'araucaria', 'bady bassitt', 'montenegro', 'flores da cunha', 'laurentino', 'uruacu', 'videira', 'timbo', 'angra dos reis', 'coronel fabriciano', 'formosa', 'igaracu do tiete', 'cafelandia', 'auriflama', 'estancia velha', 'dores de campos', 'ipatinga', 'hortolandia', 'curitibanos', 'itauna', 'sao pedro', 'sombrio', 'imbituba', 'lauro de freitas', 'leme', 'brejao', 'aguas claras', 'jambeiro', 'pirituba', 'cornelio procopio', 'massaranduba', 'medianeira', 'cordeiropolis', 'campo do meio', 'mombuca', 'poa', 'monte alto', 'horizontina', 'icara', 'tocantins', 'marica', 'picarras', 'resende', 'campina grande', 'pederneiras', 'laguna', 'ampere', 'varzea alegre', 'ipua', 'muqui', 'timoteo', 'pouso alegre', 'governador valadares', 'jaragua', 'itabira', 'ilicinea', 'campo mourao', 'pinhalao', 'imbituva', 'taruma', 'domingos martins', 'messias targino', 'ipe', 'muriae', 'cruzeiro', 'entre rios do oeste', 'ubatuba', 'pacatuba', "arraial d'ajuda (porto seguro)", 'presidente epitacio', 'pitangueiras', 'divisa nova', 'tres coroas', 'caratinga', 'pirassununga', 'arinos', 'pato bragado', 'ararangua', 'holambra', 'mandirituba', 'vicente de carvalho', 'sertanopolis', 'pedrinhas paulista', 'sabara', 'oliveira', 'itau de minas', 'japira', 'california', "sao miguel d'oeste", 'teresina', 'monte alegre do sul', 'lagoa santa', 'guarapuava', 'sinop', 'joao pinheiro', 'santa catarina', 'aracaju', 'torres', 'pedregulho', 'goioere', 'ponte nova', 'mamanguape', 'laranjeiras do sul', 'mirandopolis', 'jaciara', 'juazeiro do norte', 'paracambi', 'vargem grande paulista', 'mandaguari', 'sao miguel do oeste', 'guiricema', 'arvorezinha', 'santa terezinha de goias', 'formosa do oeste', 'orleans', 'nhandeara', 'coxim', 'irece', 'brotas', 'bom jesus dos perdoes', 'itaporanga', 'rolante', 'santa cecilia', 'lambari', 'colatina', 'guara', 'marialva', 'sao francisco do sul', 'serra redonda', 'bom jardim', 'barro alto', 'concordia', 'piracanjuba', 'campanha', 'uruguaiana', 'santo antonio de posse', 'sao joaquim da barra', 'vespasiano', 'serrana', 'igrejinha', 'santo antonio da patrulha', 'barra velha', 'saquarema', 'congonhal', 'itaborai', 'janauba', 'tiete', 'ouro fino', 'campos dos goytacazes', 'sao bento', 'joao monlevade', 'luziania', 'floresta', 'braco do norte', 'portoferreira', 'tres rios', 'paicandu', 'santo angelo', 'parnamirim', 'vera cruz', 'porto velho', 'mucambo', 'prados', 'pilar do sul', 'novo horizonte', 'fronteira', 'aperibe', 'parai', 'guaimbe', 'congonhas', 'carmo do cajuru', 'portao', 'sao vicente', 'ronda alta', 'olimpia', 'extrema', 'mairinque', 'imigrante', 'marapoama', 'cerqueira cesar', 'andira', 'ivoti', 'bertioga', 'almirante tamandare', 'bebedouro', 'cravinhos', 'monte siao', 'bage', 'descalvado', 'erechim', 'buritama', 'caieiras', 'nova lima', 'varzea paulista', 'mineiros do tiete', 'neopolis', 'itapui', 'miguelopolis', 'sao pedro da aldeia', 'campina das missoes', 'castro pires', 'fernando prestes', 'camboriu', 'nova petropolis', 'jarinu', 'taio', 'passos', 'mococa', 'paraiba do sul', 'viana', 'monteiro lobato', 'bahia', 'rio branco', 'jales', 'luiz alves', 'araquari', 'bonfinopolis de minas', 'garuva', 'presidente getulio', 'santo antonio de padua', 'guanhaes', 'louveira', 'vassouras', 'ji parana', 'alambari', 'abadia de goias', 'cataguases', 'aparecida', 'paraiso do sul', 'embu guacu', 'campo magro', 'eusebio', 'sao luis', 'nova trento', 'teixeira soares', 'sao joao da boa vista', 'macatuba', 'sao sebastiao', 'itapeva', 'camanducaia', 'tres de maio', 'orlandia', 'bombinhas', 'parana', 'centro', 'afonso claudio', 'rio das pedras', 'engenheiro coelho', 'eunapolis', 'campos novos', 'minas gerais', 'terra boa', 'manaus', 'xaxim', 'rio grande', 'francisco morato', 'clementina', 'rio negrinho', 'soledade', 'imbe', 'ilheus', 'bocaiuva do sul', 'socorro', 'mateus leme', 'rio do oeste', 'mandaguacu', 'bofete', 'mage', 'rio verde', 'alvares machado', 'santa rosa de viterbo', 'pedro leopoldo', 'ouro preto', 'carmo da mata', 'cordilheira alta', 'caucaia', 'guanambi', 'ibia', 'condor', 'santa maria da serra', 'ibirite', 'avare', 'itirapina', 'palotina', 'vitoria de santo antao', 'bandeirantes', 'aparecida de goiania', 'irati', 'tambau', 'guaratingueta', 'cacador', 'ourinhos', 'dracena', 'sao sebastiao da grama', 'guariba', 'cachoeira do sul', 'feira de santana', 'cianorte', 'presidente bernardes', 'cananeia', 'queimados', 'gama', 'ipaussu', 'alvorada', 'paranavai', 'sapiranga', 'itapema', 'colorado', 'santa cruz do sul', 'triunfo', 'uniao da vitoria', 'jussara', 'barrinha', 'porto seguro']

In [35]:
city_corrections.update({
    "sao miguel d'oeste": "sao miguel do oeste",
    "portoferreira": "porto ferreira",
})

In [36]:
df['seller_city'] = df['seller_city'].replace(city_corrections)

In [37]:
print(df['seller_city'].value_counts().index.tolist())

['sao paulo', 'curitiba', 'rio de janeiro', 'belo horizonte', 'ribeirao preto', 'guarulhos', 'ibitinga', 'santo andre', 'campinas', 'maringa', 'sao bernardo do campo', 'sao jose do rio preto', 'sorocaba', 'osasco', 'brasilia', 'porto alegre', 'londrina', 'goiania', 'joinville', 'blumenau', 'sao caetano do sul', 'franca', 'florianopolis', 'sao jose dos campos', 'caxias do sul', 'mogi das cruzes', 'limeira', 'santos', 'marilia', 'cascavel', 'jundiai', 'maua', 'bauru', 'barueri', 'sao carlos', 'sao jose dos pinhais', 'rio claro', 'uberlandia', 'presidente prudente', 'piracicaba', 'contagem', 'taboao da serra', 'atibaia', 'araraquara', 'carapicuiba', 'praia grande', 'birigui', 'brusque', 'juiz de fora', 'cotia', 'itajai', 'arapongas', 'catanduva', 'porto ferreira', 'americana', 'pinhais', 'itaquaquecetuba', 'salto', 'pedreira', 'diadema', 'santana de parnaiba', 'canoas', 'jaragua do sul', 'mogi guacu', 'palhoca', 'apucarana', 'jacarei', 'colombo', 'divinopolis', 'indaiatuba', 'niteroi', 'toledo', 'assis', "santa barbara d'oeste", 'novo hamburgo', 'sao roque', 'salvador', 'sao goncalo', 'fortaleza', 'valinhos', 'fazenda rio grande', 'santa rita do sapucai', 'claudio', 'uba', 'guaruja', 'ponta grossa', 'petropolis', 'ribeirao pires', 'taubate', 'lencois paulista', 'sao jose', 'foz do iguacu', 'amparo', 'recife', 'betim', 'nova friburgo', 'nova iguacu', 'lajeado', 'sumare', 'pocos de caldas', 'vila velha', 'tubarao', 'penapolis', 'braganca paulista', 'itapevi', 'jaci', 'itapecerica da serra', 'paulinia', 'itu', 'capivari', 'mirassol', 'jaguariuna', 'barretos', 'jau', 'araguari', 'cachoeiro de itapemirim', 'votorantim', 'rio do sul', 'garca', 'campo grande', 'botucatu', 'votuporanga', 'tupa', 'formiga', 'borda da mata', 'varginha', 'francisco beltrao', 'umuarama', 'barra mansa', 'criciuma', 'fernandopolis', 'vitoria', 'aracatuba', 'sete lagoas', 'itatiba', 'balneario camboriu', 'ferraz de vasconcelos', 'serra', 'morrinhos', 'sarandi', 'jacutinga', 'mesquita', 'boituva', 'rolandia', 'cachoeirinha', 'lages', 'navegantes', 'sao jose do rio pardo', 'mogi mirim', 'montes claros', 'cariacica', 'anapolis', 'guaratuba', 'carazinho', 'araras', 'serra negra', 'tatui', 'santa maria', 'bento goncalves', 'venancio aires', 'artur nogueira', 'aruja', 'chapeco', 'batatais', 'osvaldo cruz', 'loanda', 'duque de caxias', 'pelotas', 'marechal candido rondon', 'vargem grande do sul', 'sao joao de meriti', 'conselheiro lafaiete', 'tres coracoes', 'cambe', 'campo largo', 'uberaba', 'macae', 'tabatinga', 'pompeia', 'sao bento do sul', 'laranjal paulista', 'santa terezinha de itaipu', 'suzano', 'itapetininga', 'itaipulandia', 'videira', 'pinhalzinho', 'pitanga', 'patos de minas', 'registro', 'cafelandia', 'armacao dos buzios', 'lorena', 'campo limpo paulista', 'rodeio', 'indaial', 'estancia velha', 'auriflama', 'imbituba', 'cajamar', 'lauro de freitas', 'ipira', 'baependi', 'tiradentes', 'timbo', 'bariri', 'nova odessa', 'andradas', 'natal', 'embu das artes', 'cosmopolis', 'teresopolis', 'belford roxo', 'lagoa da prata', 'conchal', 'pradopolis', 'cuiaba', 'gaspar', 'alfenas', 'volta redonda', 'araucaria', 'bady bassitt', 'viamao', 'tanabi', 'canoinhas', 'barbacena', 'caruaru', 'santa rosa', 'uruacu', 'araxa', 'farroupilha', 'nilopolis', 'franco da rocha', 'treze tilias', 'paulo lopes', 'rio bonito', 'castro', 'porto belo', 'coronel fabriciano', 'sao ludgero', 'joao pessoa', 'garopaba', 'jaguaruna', 'formosa', 'dois corregos', 'flores da cunha', 'campo bom', 'echapora', 'guaira', 'jaboticabal', 'laurentino', 'angra dos reis', 'montenegro', 'itauna', 'dores de campos', 'ipatinga', 'hortolandia', 'curitibanos', 'mairipora', 'sao joao del rei', 'vicosa', 'pato branco', 'sao miguel do oeste', 'igaracu do tiete', 'itajobi', 'sao pedro', 'sombrio', 'xanxere', 'ribeirao das neves', 'sao leopoldo', 'caucaia', 'muqui', 'cianorte', 'aguas claras', 'itirapina', 'jambeiro', 'pirituba', 'cornelio procopio', 'massaranduba', 'medianeira', 'alvares machado', 'santa rosa de viterbo', 'pedro leopoldo', 'ouro preto', 'cachoeira do sul', 'soledade', 'rio negrinho', 'tambau', 'irati', 'aparecida de goiania', 'pederneiras', 'campina grande', 'resende', 'caratinga', 'tres coroas', 'leme', 'cordilheira alta', 'carmo da mata', 'clementina', 'francisco morato', 'rio grande', 'sao francisco do sul', 'imbituva', 'guaimbe', 'laguna', 'divisa nova', 'pitangueiras', 'presidente epitacio', "arraial d'ajuda (porto seguro)", 'teresina', 'california', 'japira', 'itau de minas', 'oliveira', 'sabara', 'pedrinhas paulista', 'holambra', 'camanducaia', 'novo horizonte', 'pilar do sul', 'ubatuba', 'entre rios do oeste', 'cruzeiro', 'muriae', 'ipe', 'messias targino', 'domingos martins', 'ampere', 'mucambo', 'porto velho', 'paracambi', 'bom jardim', 'serra redonda', 'serrana', 'congonhas', 'horizontina', 'taruma', 'pirassununga', 'juazeiro do norte', 'pedregulho', 'torres', 'aracaju', 'santa catarina', 'joao pinheiro', 'pacatuba', 'parai', 'aperibe', 'fronteira', 'tres de maio', 'monte alto', 'poa', 'mombuca', 'campo do meio', 'cordeiropolis', 'monte siao', 'garuva', 'bonfinopolis de minas', 'passos', 'tocantins', 'lagoa santa', 'monte alegre do sul', 'rolante', 'itaporanga', 'araquari', 'santo antonio da patrulha', 'itaborai', 'nhandeara', 'orleans', 'formosa do oeste', 'santa terezinha de goias', 'icara', 'piracanjuba', 'concordia', 'irece', 'coxim', 'mandaguari', 'vargem grande paulista', 'marialva', 'guara', 'sinop', 'guarapuava', 'saquarema', 'barra velha', 'ouro fino', 'tiete', 'colatina', 'lambari', 'santa cecilia', 'braco do norte', 'floresta', 'luziania', 'joao monlevade', 'sao bento', 'campos dos goytacazes', 'sapiranga', 'bom jesus dos perdoes', 'brotas', 'jales', 'rio branco', 'bahia', 'monteiro lobato', 'viana', 'paraiba do sul', 'mococa', 'mandirituba', 'rio verde', 'mage', 'bofete', 'picarras', 'marica', 'jaragua', 'governador valadares', 'congonhal', 'guiricema', 'santo antonio de posse', 'uruguaiana', 'campanha', 'jaciara', 'igrejinha', 'vera cruz', 'parnamirim', 'santo angelo', 'paicandu', 'tres rios', 'paranavai', 'alvorada', 'ipaussu', 'barro alto', 'luiz alves', 'itapui', 'neopolis', 'cravinhos', 'bebedouro', 'almirante tamandare', 'bertioga', 'ivoti', 'andira', 'cerqueira cesar', 'marapoama', 'imigrante', 'mairinque', 'janauba', 'vespasiano', 'sao joaquim da barra', 'arvorezinha', 'bage', 'taio', 'jarinu', 'nova petropolis', 'camboriu', 'extrema', 'olimpia', 'ronda alta', 'sao vicente', 'portao', 'carmo do cajuru', 'fernando prestes', 'castro pires', 'campina das missoes', 'sao pedro da aldeia', 'miguelopolis', 'varzea paulista', 'nova lima', 'mirandopolis', 'laranjeiras do sul', 'mamanguape', 'ponte nova', 'goioere', 'sertanopolis', 'vicente de carvalho', 'ipua', 'varzea alegre', 'guaratingueta', 'caieiras', 'buritama', 'erechim', 'descalvado', 'afonso claudio', 'centro', 'parana', 'bombinhas', 'nova trento', 'sao luis', 'eusebio', 'campo magro', 'embu guacu', 'paraiso do sul', 'aparecida', 'cataguases', 'abadia de goias', 'alambari', 'ji parana', 'mineiros do tiete', 'mandaguacu', 'rio do oeste', 'mateus leme', 'socorro', 'bocaiuva do sul', 'ilheus', 'imbe', 'vassouras', 'louveira', 'guanhaes', 'santo antonio de padua', 'presidente getulio', 'campos novos', 'eunapolis', 'engenheiro coelho', 'rio das pedras', 'xaxim', 'manaus', 'terra boa', 'minas gerais', 'avare', 'ibirite', 'santa maria da serra', 'condor', 'ibia', 'guanambi', 'orlandia', 'itapeva', 'sao sebastiao', 'macatuba', 'sao joao da boa vista', 'teixeira soares', 'feira de santana', 'uniao da vitoria', 'triunfo', 'guariba', 'sao sebastiao da grama', 'dracena', 'ourinhos', 'cacador', 'gama', 'queimados', 'cananeia', 'presidente bernardes', 'bandeirantes', 'vitoria de santo antao', 'palotina', 'porto seguro', 'ararangua', 'pato bragado', 'arinos', 'prados', 'santa cruz do sul', 'colorado', 'itapema', 'pinhalao', 'campo mourao', 'ilicinea', 'itabira', 'barrinha', 'jussara', 'pouso alegre', 'timoteo', 'brejao']

##All are almost cleaned but their is still some city which named as state

In [38]:
suspicious = [
    'santa catarina',
    'parana',
    'bahia',
    'tocantins',
    'minas gerais',
    'centro',
    'pirituba',
    'vicente de carvalho',
    'jaragua',
    'arraial d\'ajuda (porto seguro)',
    'aguas claras'
]

df[df['seller_city'].isin(suspicious)][
    ['seller_zip_code_prefix', 'seller_city', 'seller_state']
].sort_values('seller_zip_code_prefix')

      seller_zip_code_prefix                     seller_city seller_state
2573                    5141                        pirituba           SP
287                    11450             vicente de carvalho           SP
2183                   35660                          centro           MG
424                    36512                       tocantins           SP
2380                   37165                    minas gerais           MG
874                    45816  arraial d'ajuda (porto seguro)           BA
405                    48602                           bahia           BA
2589                   71900                    aguas claras           SP
2965                   76330                         jaragua           GO
2188                   87083                          parana           PR
1050                   88135                  santa catarina           SC

In [39]:
city_mapping = {
    'pirituba': 'sao paulo',
    'vicente de carvalho': 'guaruja',
    'arraial d\'ajuda (porto seguro)': 'porto seguro',
    'jaragua': 'jaragua'
}

In [40]:
df['seller_city'] = df['seller_city'].replace(city_mapping)

In [41]:
df['seller_city'].nunique()

554

In [42]:
df['seller_state'].nunique()

23

In [43]:
df['seller_state'].value_counts()

seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
CE      13
PE       9
PB       6
MS       5
RN       5
MT       4
RO       2
SE       2
AC       1
PI       1
MA       1
AM       1
PA       1
Name: count, dtype: int64

In [44]:
print(df['seller_state'].value_counts().index.tolist())

['SP', 'PR', 'MG', 'SC', 'RJ', 'RS', 'GO', 'DF', 'ES', 'BA', 'CE', 'PE', 'PB', 'MS', 'RN', 'MT', 'RO', 'SE', 'AC', 'PI', 'MA', 'AM', 'PA']

##Thei is no Error in State column

In [45]:
df.sample(5)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
2975,a1544b9ea0b2390e020537d4daa89049,13211,jundiai,SP
2910,c1ed9e3daf6154542826a6996af0fb8c,88308,itajai,SC
2280,a806a4bb063ea7ca6d374eafa50a6058,29161,serra,ES
141,ebef8d8c92b4fd3226e5d407bbff21ac,14020,ribeirao preto,SP
2697,1f1bb1f0859883505541bdd6606193e5,2124,sao paulo,SP

In [46]:
df[['seller_zip_code_prefix','seller_city']].drop_duplicates().shape[0]

2258

##the 5-digit zip code prefix is not always the same for an entire city.

In [47]:
df.to_csv('cleaned_sellers.csv',index=False)
from google.colab import files
files.download('cleaned_sellers.csv')